=== LeoonLiang/xuanwu-fozu-lingqian/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "玄武山佛祖灵签",
  "type": "object",
  "additionalProperties": true,
  "properties": {
    "签号": { "type": "string" },
    "签名": { "type": "string" },
    "签文类型": { "type": "string" },
    "卦象": { "type": "string" },
    "生肖": { "type": "string" },
    "签文简介": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "戏文": { "type": "string" },
        "诗曰": { "type": "string" },
        "内兆": { "type": "string" }
      }
    },
    "家宅运势": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "签文": { "type": "string" },
        "解曰": { "type": "string" }
      }
    },
    "岁君签": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "总诗": { "type": "string" },
        "年龄运势": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "年龄": { "type": "string" },
              "男": { "type": "string" },
              "女": { "type": "string" }
            }
          }
        }
      }
    },
    "生意": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "生意": { "type": "string" },
        "生意解曰": { "type": "string" },
        "开铺": { "type": "string" },
        "合伙": { "type": "string" },
        "置货": { "type": "string" }
      }
    },
    "出外": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "出外": { "type": "string" }
      }
    },
    "谋望求财": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "谋望": { "type": "string" },
        "谋望解曰": { "type": "string" },
        "求财": { "type": "string" }
      }
    },
    "学艺功名": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "学艺": { "type": "string" },
        "功名": { "type": "string" }
      }
    },
    "行舟六畜": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "行舟": { "type": "string" },
        "六畜": { "type": "string" },
        "猪羊": { "type": "string" },
        "草龙": { "type": "string" },
        "三鸟": { "type": "string" },
        "田蚕": { "type": "string" }
      }
    },
    "移徙": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "移徙": { "type": "string" }
      }
    },
    "行人": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "诗": { "type": "string" },
        "解曰": { "type": "string" }
      }
    },
    "婚姻": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "婚姻": { "type": "string" },
        "解曰": { "type": "string" }
      }
    },
    "官讼": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "官讼": { "type": "string" },
        "解曰": { "type": "string" }
      }
    },
    "失物": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "失物": { "type": "string" },
        "解曰": { "type": "string" }
      }
    },
    "占病": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "占病": { "type": "string" },
        "解曰": { "type": "string" }
      }
    },
    "其他": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "灶君": { "type": "string" },
        "阳基": { "type": "string" },
        "六甲": { "type": "string" },
        "子息": { "type": "string" },
        "祖山": { "type": "string" },
        "青草": { "type": "string" }
      }
    }
  }
}

=== LeoonLiang/xuanwu-fozu-lingqian/data/45.json
{
  "签号": "第四十五签",
  "签名": "罗成娶妻",
  "签文类型": "蟾宫折桂之兆",
  "卦象": "上上之卦",
  "生肖": "子鼠",
  "签文简介": {
    "戏文": "唐程咬金代罗成议定一门亲事，罗成不就，其未婚妻美淑且多情，因羡罗成英武，终相思而亡。程咬金愤极，蓄意惩罚罗成，骗其为娶美姿娘，实乃替娶丑史大奈。迎娶路上，史大奈暴王，罗成前期魂附丑女身复活，丰颜姣好如旧，终了旧愿，与罗成遂百年欢好。",
    "诗曰": "一鸟庭前立，胜如争在先;深潭垂钓饵，得鲤任君才。",
    "内兆": "万物萌芽"
  },
  "家宅运势": {
    "签文": "门冷户衰百怪生，人财两散梦魂惊，如今君问平安日，庶民人口进财丁。",
    "解曰": "人财冲冠防疾难破财是非火盗，男女不和兄弟分居宜求佛祖保平安，又嫌门字灶君分金不美，宜修改合课居住财丁昌盛。"
  },
  "岁君签": {
    "总诗": "风雷鼓舞播乾坤，万物萌芽尽发生，如今君问平安日，待至秋冷月又明。",
    "年龄运势": [
      {
        "年龄": "1-3岁",
        "男": "小孩根基足养，但防春夏月灾难波阻，宜吓月娘化吉，交秋返运出入平安。（以诗文为准）",
        "女": "小女根苗浅薄，惟防春夏月小疾多事，宜吓月娘化吉，交秋返运出入平安。（以诗文为准）"
      },
      {
        "年龄": "4-7岁",
        "男": "小儿现年运限未遂，虽精通，但防春夏月多生波阻，水边小心，吓月娘，交秋返运平安。（以诗文为准）",
        "女": "小女运限未美，惟防春夏月灾难水厄，逢水边小心，吓月娘化吉，交秋返运平安。（以诗文为准）"
      },
      {
        "年龄": "8-12岁",
        "男": "小儿之卦时令未美，春夏月尤防小疾多事，吓月娘化吉，交秋转运平安。（以诗文为准）",
        "女": "小女运度未佳，惟防执僻，又防小疾波阻，春夏月守旧，吓月娘化吉，交秋返运平安。（以诗文为准）"
      },
      {
        "年龄": "13-15岁",
        "男": "童造时令未佳，不可执僻，春夏月皮肤小疾，守旧，吓月娘，交秋返运平安。（以诗文为准）",
        "女": "小女时运不佳，人虽清秀，但防春夏月波阻，夜勿独行，吓月娘交秋返运平安。（以诗文为准）"
      },
      {
        "年龄": "16-17岁",
        "男": "祥造运度未美，人虽聪明特达，但防二、四、六月小疾波阻，吓天地化吉，交秋返运平安。（以诗文为准）",
        "女": "玉造时令未佳，人虽贤玉，惟防波阻，春夏月切勿独行，吓月娘，交秋返运平安。（以诗文为准）"
      },
      {
        "年龄": "18-29岁",
        "男": "英造步运不佳，万物萌芽虽特达，但防春夏月小人祸非，不可迫性，交秋贵人扶助，可得财喜平安。（以诗文为准）",
        "女": "美造现年时运不佳，虽是贤淑，但防小疾多事，春夏月守旧，夜时勿远出独行，交秋转运出入平安。（以诗文为准）"
      },
      {
        "年龄": "30-55岁",
        "男": "乾造步运未美，人虽老练，但嫌迫性，春夏月防小人嫁祸，凡事从正，交秋转运有贵人扶助平安。（以诗文为准）",
        "女": "坤造行运不美，虽助益家庭，但防暗疾口舌，凡事忍住，吓月娘，交秋平安。（以诗文为准）"
      },
      {
        "年龄": "56-69岁",
        "男": "台造步运不美，虽忠诚，惟防春夏月灾难，歹人不测之祸，闲事切勿近理，交秋转运平安。（以诗文为准）",
        "女": "坤造现年运度美中不足，虽有内助之称，但嫌操心暗疾，春夏月守旧，交秋平安。（以诗文为准）"
      },
      {
        "年龄": "70岁以上",
        "男": "吉造老运不旺，但嫌人老迫性，防春夏月交脱，上落小心，守旧，交秋平安。（以诗文为准）",
        "女": "妇造老运不旺，但防暗疾跌地之厄，守旧，喜孝堂勿近，交秋可卜大造平安。（以诗文为准）"
      }
    ]
  },
  "生意": {
    "生意": "凡事通灵营生意，春夏似月云遮去，秋冬贵人相扶助，借力谋财好局势。",
    "生意解曰": "按旧来经营恐吓有阻失，要创新业防初时亏本，要和人合伙移他人福，可得厚财",
    "开铺": "卜开铺之卦得鲤鱼，看君的才能，上春恐吓有阻失，秋后有贵人扶助，能上蟾宫折桂，可得厚财利。",
    "合伙": "卜合伙之卦叶吉如万物逢春之兆，宜同心同德协力经营，秋后可得厚财利也!",
    "置货": "卜今年置货，上春防亏本，但要立胆智置而留之，候交秋冬月，可得财利。"
  },
  "出外": {
    "出外": "卜出外一事签文虽安然，但嫌心意未定，要有胆智敢往，五八月有贵人重重。"
  },
  "谋望求财": {
    "谋望": "本是聪明特达人，恰似明月云遮清，等闲借得东风力，吹去浮云又复明。",
    "谋望解曰": "谋事初时时运未通，防小人阻隔，但又有贵人重重，交三，五月成就，肖牛者更妙",
    "求财": "正财上春利薄宜立志气维持秋后转运有厚利可得，偏财要托他人之福，要忍口舌是非!"
  },
  "学艺功名": {
    "学艺": "卜学技艺之卦叶吉，但君须勤学苦练，定能得名师传真艺，掌握技艺本领，肖牛者学之更妙。",
    "功名": "文武皆及第，荣宗耀祖，捐纳及营伍有纳升。"
  },
  "行舟六畜": {
    "行舟": "行舟顺风得利，春夏中吉，秋冬大利大吉。",
    "六畜": "初有小阻不必疑，借得神力魔可驱。莫听旁人东西说，月圆秋交有大利。",
    "猪羊": "",
    "草龙": "",
    "三鸟": "",
    "田蚕": ""
  },
  "移徙": {
    "移徙": ""
  },
  "行人": {
    "诗": "",
    "解曰": ""
  },
  "婚姻": {
    "婚姻": "本来婚姻要团圆，无奈旁人说乱言，迟定不如早定好，管教男女共完全。",
    "解曰": "虽有一对好姻缘，但有小人破说，不要乱听闲言宜速定配，成之大吉"
  },
  "官讼": {
    "官讼": "",
    "解曰": ""
  },
  "失物": {
    "失物": "",
    "解曰": ""
  },
  "占病": {
    "占病": "",
    "解曰": ""
  },
  "其他": {
    "灶君": "",
    "阳基": "",
    "六甲": "",
    "子息": "",
    "祖山": "",
    "青草": ""
  }
}

=== LeoonLiang/xuanwu-fozu-lingqian/data/17.json
{
  "签号": "第十七签",
  "签名": "王省就亲",
  "签文类型": "一牛二尾之兆",
  "卦象": "中平之卦",
  "生肖": "辰龙",
  "签文简介": {
    "戏文": "恶少番奉欲霸余三姑为妻。三姑随夫王省避居姑母家中。表兄秦招吉贪三姑色，醉王省，冒报王省名，夜敲三姑居室相戏，欲乱之时适番奉使白面虎寻杀王省，秦乃被错杀，王遂坐罪。幸包公查访重审，案情始大白。",
    "诗曰": "才子遇佳人，红霞映碧波;文书今日至，凡事起荣华。",
    "内兆": "枯树生枝"
  },
  "家宅运势": {
    "签文": "莫将怪梦作闲因，邪摩私祸不临神，自是行藏千里合，岂因病小危难消。",
    "解曰": "吉宅人口可得喜气临门，但嫌六杀占宅，恐吓防六，九，十二月疾难口舌失财，向佛祖奉经保平安，求达摩祖师香火安门上祭化则财丁兴旺。"
  },
  "岁君签": {
    "总诗": "当时得意反成痴，今日忧疑事不危，若遇贵人相接引，十年桔树又生枝。",
    "年龄运势": [
      {
        "年龄": "1-3岁",
        "男": "小孩根苗足养，惟有春夏月小疾，守旧，幸吉星守度，寿命绵长平安。",
        "女": "小女根苗足养，旺益上人并茂，夏月小疾无妨，吉星守度平安。"
      },
      {
        "年龄": "4-7岁",
        "男": "小儿运限顺遂，生性天真，旺益上人并茂，春夏月小疾无妨，寿命绵长。",
        "女": "小女运限叶吉，天真活泼，利益上人春夏月小疾无妨，吉星守度平安。"
      },
      {
        "年龄": "8-12岁",
        "男": "童造运度顺遂，各事开窍，宜培养入学读书，定卜进步，吉星守命出入平安。",
        "女": "小女运度叶吉，各事伶俐，旺益上人并茂，夏月小疾无妨，吉星守度出入平安。"
      },
      {
        "年龄": "13-15岁",
        "男": "童造今年交上运，聪明开窍，宜入学读书，定卜远景有望，且出入平安。",
        "女": "玉造现年交上美运，旺益家门，夏月虽有小疾无妨，有吉星照身平安。"
      },
      {
        "年龄": "16-17岁",
        "男": "祥造时运亨通，如枯木生枝，各事通能，认真学习文化，前途进展，出入平安。",
        "女": "玉造交上美运，技巧清秀，有助益家庭之心，夏月虽有小疾无妨，出入平安。"
      },
      {
        "年龄": "18-29岁",
        "男": "英造步运亨通，如枯木生枝，做事有奇才机智，但凡事从正道经营，意外勿贪，有贵人扶助可得财喜。",
        "女": "玉造今年交上美运，步入佳景，宜习收益，春夏月虽有小疾无妨，卦中吉星照身出入平安。"
      },
      {
        "年龄": "30-55岁",
        "男": "乾造步运亨通，如枯木生枝，聪明奇智，宜从正道，为人义气相交，切勿妄取，有贵人扶助可得财喜。",
        "女": "坤造行运交泰，如枯木生枝，贤淑智慧，有内助之称，但勿操迫，暗疾无妨，幸吉星守度出入平安。"
      },
      {
        "年龄": "56-69岁",
        "男": "台造步运亨通，如枯木生枝，做事忠诚，但宜宽宏大量，春夏月虽有小疾无妨，贵人扶助出入平安。",
        "女": "坤造行运交泰，如枯木生枝，虽有旺益家庭，但防暗疾之阻，宜静养，幸有吉星照身出入平安。"
      },
      {
        "年龄": "70岁以上",
        "男": "吉造老运安康，但防春夏灾疾之厄，守旧，幸贵人扶助，晚景胜前。",
        "女": "妇造老运虽有旺益子孙，但暗疾上身，忌看病人，幸吉星守命平安。"
      }
    ]
  },
  "生意": {
    "生意": "生意经营切莫贪，牢牢记住守旧框，肖牛之人防阻失，肖羊之人厚利攀。",
    "生意解曰": "生意有利可得但防阻失，经营要正直谨慎，肖羊者得厚利，肖牛者失财利",
    "开铺": "卜开铺之卦不美未开勿开，已开之钥应防盗贼火灾，肖牛者失利肖羊者可得大利。",
    "合伙": "卜合伙之卦不美失字当头，特别是肖牛者更不妙，伙计不同心有小人祸害，勿合也!",
    "置货": "卜置货物，肖牛之人定失，肖羊之人能得利，余生肖者不可贪财利则吉也。"
  },
  "出外": {
    "出外": "卜出外一事虽有贵人扶助，但又防小人生端寄祸，不可在外久住，且来来往往!"
  },
  "谋望求财": {
    "谋望": "贪多更惹祸临身，名利从来是未真，但得忧游家道乐，知他谁是百年人。",
    "谋望解曰": "谋事可成但有阻隔，做要稳重认真，不可贪心方免惹祸临身",
    "求财": "正财库取利虽有微利可得，但恐防阻失，凡事业从正道，八，十一月有财利可得，偏财有阻失勿取吉也!"
  },
  "学艺功名": {
    "学艺": "学技艺之卦，肖羊者学之定成，肖牛者勿学为宜，其他人学习，宜刻苦用工，可成功也。",
    "功名": "功名肖羊之人及未科，定可显达也。"
  },
  "行舟六畜": {
    "行舟": "行舟中吉，防凶失，合移不可也。",
    "六畜": "耕牛阻隔在今年，养猪劳苦有一期。肥猪养大及时卖，放羊牧人得财利。",
    "猪羊": "",
    "草龙": "",
    "三鸟": "",
    "田蚕": ""
  },
  "移徙": {
    "移徙": ""
  },
  "行人": {
    "诗": "",
    "解曰": ""
  },
  "婚姻": {
    "婚姻": "不须勉强费尽金，婚来合时何用寻，立志强成非好事，知人知面不知心。",
    "解曰": "婚姻大事切需要探明对方底细，不可马虎从事乱挥金钱，别把野花当红花"
  },
  "官讼": {
    "官讼": "",
    "解曰": ""
  },
  "失物": {
    "失物": "",
    "解曰": ""
  },
  "占病": {
    "占病": "",
    "解曰": ""
  },
  "其他": {
    "灶君": "",
    "阳基": "",
    "六甲": "",
    "子息": "",
    "祖山": "",
    "青草": ""
  }
}

=== LeoonLiang/xuanwu-fozu-lingqian/data/13.json
{
  "签号": "第十三签",
  "签名": "吕蒙正两世姻缘",
  "签文类型": "万物逢春之兆",
  "卦象": "大吉之卦",
  "生肖": "申猴",
  "签文简介": {
    "戏文": "吕蒙正前期刘氏守寒窑受虐而亡，转世为渔翁女，丽色而拳手不开。吕呼之，其掌顿开，渔翁女乃嫁吕，生子吕子骞，骞生孙亦贤。俱登科。",
    "诗曰": "禹门跳浪翻，鱼变化为龙;已意成君意，方为吉亨通。",
    "内兆": "脱衣换锦"
  },
  "家宅运势": {
    "签文": "今年不似去年贫，财禄重添遇贵宾，人口完成无盗贼，平安赛过九洲人。",
    "解曰": "喜气洋洋，但防疾难口舌失财盗贼之厄，门户小心皆因祖山不顺，有利宜修整合课，吓佛祖保平安，并求福灯吊门上化吉，则财丁可兴旺也。"
  },
  "岁君签": {
    "总诗": "开花结果喜逢时，赖得天官造化机，谋望求财皆遂意，衣锦还乡事可期。",
    "年龄运势": [
      {
        "年龄": "1-3岁",
        "男": "小孩根基足养，八字清秀，旺益上人并茂，上春月虽有小疾无妨，吉星守命平安。",
        "女": "小女根苗稳固，有旺益上人并茂，上春月虽有皮疾无妨，卦中吉星守命平安。"
      },
      {
        "年龄": "4-7岁",
        "男": "小儿现年亨通，天真活泼，利益上人并茂，夏月水边小心，吉星守度平安。",
        "女": "小女运限顺遂，各事伶俐，旺益上人并茂，夏月水边小心，幸吉星守命平安。"
      },
      {
        "年龄": "8-12岁",
        "男": "童造现年运度叶吉，天真伶俐，可入学校读书，定卜进行，夏月水边小心，幸吉星守命平安。",
        "女": "小女之卦时令亨通，各事活泼，有旺益上人并茂，夏月虽有小疾无妨，吉星守度平安。"
      },
      {
        "年龄": "13-15岁",
        "男": "童造运度精通，各事聪明开窍，宜培养入学校读书，定卜进步，出入平安。",
        "女": "玉造运度顺遂，活泼精巧，上春月虽有小疾无妨，吉星守命出入平安。"
      },
      {
        "年龄": "16-17岁",
        "男": "吉造现年运度亨通，如鱼化龙，聪明才干，培养入学，远景有望，而且出入平安。",
        "女": "玉造今年交上美运，如鱼化龙，助益家庭，虽有小疾无妨，吉星守度平安。"
      },
      {
        "年龄": "18-29岁",
        "男": "英造步运亨通，如鱼化龙，通能才干，可向外争取，上春月虽有小疾无妨，有贵人扶助，可得财喜平安。",
        "女": "坤造行运交泰，如鱼化龙，贤玉技巧，有助益家庭之心，上春月小疾无妨，吉星守度玉体安康也。"
      },
      {
        "年龄": "30-55岁",
        "男": "乾造步运亨通，如鱼化龙，为人才能特达，向外从正发展，有贵人扶助，可得财喜，但勿迫性平安。",
        "女": "坤造行运交佳，如鱼化龙，贤惠有内助之称，虽有些小安吉无妨，卦中吉星守命平安。"
      },
      {
        "年龄": "56-69岁",
        "男": "台造步运顺遂，为人忠诚，君家之卦如鱼化龙，上春月虽有小疾无至大害，有贵人扶助可得财运平安。",
        "女": "坤造行运亨通，可称内助，但有小暗疾无妨，忌看病人，喜孝物勿进，幸吉星守度平安。"
      },
      {
        "年龄": "70岁以上",
        "男": "福造老运得此卦太旺，虽有旺益子孙，但防灾疾跌地之厄，上春月守旧，幸贵人扶助晚景胜前平安。",
        "女": "妇造老运安康，旺益子孙，但防暗疾多灾，上春月喜孝物勿食，宜守旧，幸吉星守命，老福绵长。"
      }
    ]
  },
  "生意": {
    "生意": "市场货物能购收，精心保管把货留，莫怕初时有阻败，秋至价高利倍售。",
    "生意解曰": "生意之卦初时财利稀少，但与人交易宜立志坚持候五，九，十一月可得厚财利。",
    "开铺": "卜开铺之卦宜秋后开业可一帆风顺得财利，若春夏月开业，宜请佛祖符令贴门上化吉也。",
    "合伙": "卜合伙之卦大吉伙计宜同心同德协力经营，候交秋冬月可得大财利也。",
    "置货": "置货起初价不振，宜放心存留，候交秋月，货物定有振价，可得财利也。"
  },
  "出外": {
    "出外": "卜此出外之卦，各事亨通，有贵人扶助，应于三、五、九月往外，定有厚财利可得。"
  },
  "谋望求财": {
    "谋望": "玉体冰肌不可移，真心之有寒岁知，如今喜得阳和日，花落自然中满枝。",
    "谋望解曰": "谋事有贵人扶助，交秋月可定就，但不能三心二意应一心一意，认真谋之",
    "求财": "正财上半年稀少宜守旧刻苦经营，交五，六，十一月财利亨通，可得厚财大利，偏财初有阻隔后可得，但切须忍口舌!"
  },
  "学艺功名": {
    "学艺": "卜学艺之卦，时令合局，有贵人扶助，宜决心立志，寻得名师传艺也。",
    "功名": "功名中，衣锦荣归，若九月赴试定显达。"
  },
  "行舟六畜": {
    "行舟": "行舟先难后易，秋后出船大吉。",
    "六畜": "要问家中猪牛羊，精心饲养多吉祥。祈祷神明力保佑，猪肥牛壮财利长。",
    "猪羊": "",
    "草龙": "",
    "三鸟": "",
    "田蚕": ""
  },
  "移徙": {
    "移徙": ""
  },
  "行人": {
    "诗": "",
    "解曰": ""
  },
  "婚姻": {
    "婚姻": "才郎女貌世间稀，前缘配定不须疑，如今但愿他人准，好把聘财去定期。",
    "解曰": "郎才女貌前缘配定，美满婚姻应及早托人前往说定，定期上聘勿失良机出外;一事名事亨通有贵人扶助，应于三，五，九月往外定有厚财利可得!"
  },
  "官讼": {
    "官讼": "",
    "解曰": ""
  },
  "失物": {
    "失物": "",
    "解曰": ""
  },
  "占病": {
    "占病": "",
    "解曰": ""
  },
  "其他": {
    "灶君": "",
    "阳基": "",
    "六甲": "",
    "子息": "",
    "祖山": "",
    "青草": ""
  }
}

=== LeoonLiang/xuanwu-fozu-lingqian/data/21.json
{
  "签号": "第二十一签",
  "签名": "上帝收龟精",
  "签文类型": "鸾凤冲霄之兆",
  "卦象": "大吉之卦",
  "生肖": "子鼠",
  "签文简介": {
    "戏文": "玄天上帝修九世功德，始成正果。偶尔外出，路遇一肉牛，赞其肥美，以其心美之而犯戒遂反胃，呕出肚肠，化为龟蛇。龟蛇祸害地方，作苦百姓，玉帝察知，乃令上帝收伏龟蛇，镇于足下。",
    "诗曰": "一人持一笔，逢午壬龙飞;守园平地稳，得意上云梯。",
    "内兆": "如鲲化鹏"
  },
  "家宅运势": {
    "签文": "须宜另改旧门庭，人旺财兴百事宁，不但田蚕收十倍，更随四方任经营。",
    "解曰": "吉宅可得喜气盈门，如无喜气事就恐有孝服事到来，皆因门字分金不正门庭水字不美，宜修整改正门庭分金水字求佛祖福灯吊正门上化吉保平安。"
  },
  "岁君签": {
    "总诗": "鲲化为鹏海浪翻，阴阳交泰太平关，庶人暮有凌云志，平地雷声倚势还。",
    "年龄运势": [
      {
        "年龄": "1-3岁",
        "男": "小孩根苗足养，旺益上人并茂，正、三、五月小疾无妨，吉星守度寿命绵长。",
        "女": "小女根苗稳固，旺益上人，正、三、五月小波疾无妨，吉星守命平安。"
      },
      {
        "年龄": "4-7岁",
        "男": "小儿之卦生性天真，旺益上人，正、三、五月不可登高，小疾无妨，吉星守度平安。",
        "女": "小女运限顺遂，旺益上人，不可登高，正、三、五月守旧，小疾无妨，有吉星照身出入平安。"
      },
      {
        "年龄": "8-12岁",
        "男": "小儿运度叶吉，各事精通，培养入学，不可登高，幸吉星照身，前途有望，平安无事。",
        "女": "小女运限亨通，凡事活泼，有旺益上人并茂，虽有小疾无妨，吉星守命平安。"
      },
      {
        "年龄": "13-15岁",
        "男": "小童运度叶吉，聪明伶俐，宜入学校读书，定卜进步，远景有望，出入平安。",
        "女": "小女运度顺遂，伶俐开窍，宜习手艺，正、三、五月小疾无妨，吉星守度平安。"
      },
      {
        "年龄": "16-17岁",
        "男": "祥造步运亨通，聪明开窍，培养入学，定卜前途进展，出入平安。",
        "女": "玉造今年交上美运，技巧开明，助益家门，正、三、五月小疾无妨，玉体安康。"
      },
      {
        "年龄": "18-29岁",
        "男": "英造步运亨通，如鲲化鹏，时令特达，但勿迫性，从正发展，有贵人扶助，可得财喜，出入平安。",
        "女": "玉造行运交泰，如鲲化鹏，各事贤玉，虽有旺益家庭，但宜温柔忍性，出入平安。"
      },
      {
        "年龄": "30-55岁",
        "男": "乾造步运亨通，人虽奇才，但防正、三、五月小人平地风波，凡事戒忍，幸贵人扶助，可得财喜平安。",
        "女": "坤造行运甚佳，如鲲化鹏，但勿迫切，温柔大量，虽有小疾无妨，吉星守命可卜出入平安。"
      },
      {
        "年龄": "56-69岁",
        "男": "台造步运亨通，为人心直性迫，凡事宽怀大量，防有不测风波，幸贵人扶助出入平安。",
        "女": "坤造行运交泰，各事贤惠，但防暗疾口舌，凡事吞忍守旧，幸有吉星守度平安。"
      },
      {
        "年龄": "70岁以上",
        "男": "福造老运得此卦太旺，惟防灾难跌地之厄，早晚上落小心，幸贵人扶助平安。",
        "女": "妇造老运不旺，暗疾上身，正、三、五月守旧，喜孝物勿进，幸吉星守度平安。"
      }
    ]
  },
  "生意": {
    "生意": "生意求财要有义，偏财一点不得利，肖马之人偏财得，四面八方任行时。",
    "生意解曰": "春季生意不能得利候五，六月起似龙带雨定有财源广进，惟肖马者有偏财可得谋望;几年沉落波涛内，未得风雷志气高，今日脱身多变化，应知万里任游遨，谋事有成但防时有阻隔，用心窍候六，九月可成，但肖猴者恐惹官非失财",
    "开铺": "卜开铺卜开铺之卦叶吉，初小利宜壮胆经营交五，六月起如鱼化鹏，可得厚财利也。",
    "合伙": "卜合伙之卦大吉，但伙计要有仁义，要同心协力交五，六月起财源广进可得财利!",
    "置货": "卜置货初时有惊阻，到底渐渐亨通，应于五、六、七、八月定得大利也。"
  },
  "出外": {
    "出外": "卜出外之卦叶吉有贵人扶助可于三，五月往外有厚利可得各事平安!"
  },
  "谋望求财": {
    "谋望": "几年沉落波涛内，未得风雷志气高。今日脱身多变化，应知万里任遨游。",
    "谋望解曰": "谋事有成，但防时有阻隔，用心窍，候六、九月可成，但肖猴者恐惹官非失财。",
    "求财": "正财库取利上春财利稀少，但宜刻苦经营秋厚转运，各事亨通可得厚利偏财唯肖马羊者得之!"
  },
  "学艺功名": {
    "学艺": "卜学艺之卦叶吉，按签文上春恐有阻隔，宜秋后学之，定能成功，手艺随身也。",
    "功名": "功名成也，肖牛羊之人逢午未更能显达。"
  },
  "行舟六畜": {
    "行舟": "行舟初时不顺，后来行之，顺风得利。",
    "六畜": "六畜有阻在春光，求神拜佛保平安。猪羊兴旺秋月后，快肥快大人乐观。",
    "猪羊": "",
    "草龙": "",
    "三鸟": "",
    "田蚕": ""
  },
  "移徙": {
    "移徙": ""
  },
  "行人": {
    "诗": "",
    "解曰": ""
  },
  "婚姻": {
    "婚姻": "精男巧女两相当，配合婚姻启后昌，此际好求鸾风偶，迟延悔过费思量。",
    "解曰": "精男巧女配合大吉，但要速速下聘办理，不可拖延，若迟恐祸变也"
  },
  "官讼": {
    "官讼": "",
    "解曰": ""
  },
  "失物": {
    "失物": "",
    "解曰": ""
  },
  "占病": {
    "占病": "",
    "解曰": ""
  },
  "其他": {
    "灶君": "",
    "阳基": "",
    "六甲": "",
    "子息": "",
    "祖山": "",
    "青草": ""
  }
}

=== LeoonLiang/xuanwu-fozu-lingqian/data/11.json
{
  "签号": "第十一签",
  "签名": "武吉卖柴",
  "签文类型": "久病逢医之兆",
  "卦象": "大吉之卦",
  "生肖": "戌狗",
  "签文简介": {
    "戏文": "武吉将入市，姜尚劝勿往，言必伤人命。武吉挑柴市卖，遇文王车架，忙避之，人担误毙门官王相，文王命画地为牢，竖木为吏囚之。武吉思母，恸。散宜生奏上允其先回家事母，然后归偿命。后武吉因引见姜尚，文王免其罪，并封为武德将军。",
    "诗曰": "红日当天照，光辉遍四方;西川人着锦，红紫满长春。",
    "内兆": "如日之升"
  },
  "家宅运势": {
    "签文": "家旺人兴百事宜，田蚕加倍在秋期，但防阴人生疾病，见喜消灾事可知。",
    "解曰": "吉宅人口可得喜气，但防疾难口舌涉财，是厝内有神恩土德，宜择日改谢清楚，又嫌祖山不顺有利宜修整壮旺，可得财丁兴旺。"
  },
  "岁君签": {
    "总诗": "囚人出狱公事休，却买甜瓜上酒楼，偶遇故人同畅饮，酒钱不了义相绕。",
    "年龄运势": [
      {
        "年龄": "1-3岁",
        "男": "小孩根苗足养，八字清格，旺益上人，上春月小疾无妨，吉星守岁平安。",
        "女": "小女根苗足养，夏月虽有小皮疾无妨，卦中有吉星守命，出入平安。"
      },
      {
        "年龄": "4-7岁",
        "男": "小儿之卦叶吉，生性天真活泼，旺益上人并茂，春夏月小疾无妨，出入平安。",
        "女": "小女之卦顺遂，各事伶俐活泼，旺益上人并茂，春夏月小疾无妨，出入平安。"
      },
      {
        "年龄": "8-12岁",
        "男": "童造现年交上运，各事开窍，宜培养入学读书，定卜进步，而且出入平安。",
        "女": "玉造现年运度顺遂，技巧活泼，春夏月虽有小波阻无妨，吉星守命平安。"
      },
      {
        "年龄": "13-15岁",
        "男": "童造运度亨通，聪明开窍，宜入学读书，定卜前途有望，出入平安。",
        "女": "玉造现年交上美运，如月之明，技巧伶俐，春夏月虽有小疾无妨，吉星守命平安。"
      },
      {
        "年龄": "16-17岁",
        "男": "吉造步运亨通，如日东升，做事聪明，培养入学，贵人扶助，小疾无妨平安。",
        "女": "玉造今年交上美运，如月之明，技巧贤玉，春夏月小疾无妨，吉星守命平安。"
      },
      {
        "年龄": "18-29岁",
        "男": "英造步运亨通，如日东升，奇才特达，可向外发展，但勿迫性，有贵人扶助，可得财喜，出入平安。",
        "女": "玉造行运交泰，如月之明，各事贤玉技巧，春夏月虽有小疾无妨，卦中有吉星守命平安。"
      },
      {
        "年龄": "30-55岁",
        "男": "乾造步运亨通，如日东升，做事老练，春夏月小疾口舌无妨，宜从正经营，有贵人扶助可得财星。",
        "女": "坤造行运交泰，如月之明，贤淑智慧，虽有小疾无妨，勿操迫，幸卦中有吉星守命出入平安。"
      },
      {
        "年龄": "56-69岁",
        "男": "台造步运亨通，如日东升，老练忠诚，可向外发展，定卜有贵人扶助，可得财运出入平安。",
        "女": "坤造行运交泰，如月之明，凡事勿操迫，春夏月虽有小疾无妨，幸吉星守度平安。"
      },
      {
        "年龄": "70岁以上",
        "男": "台造老运安康，惟防春夏月灾疾，守旧，幸福星扶照晚景胜前平安。",
        "女": "坤造老运康泰，旺益子孙，春夏月暗疾无妨，吉星守度，出入平安。"
      }
    ]
  },
  "生意": {
    "生意": "灾过运来得意开，上年赫神恩要还，春夏应防风雨阻，秋冬时节财利来。",
    "生意解曰": "生意初时利薄又防阻隔，交易宜从正道勿贪心妄取六，八，十一月有贵人可得厚财",
    "开铺": "卜开铺之卦宜先改谢前年神恩，十一月应防劫厄，上春有阻勿灰心，秋后可得利。",
    "合伙": "合伙经营必先改谢神恩伙计之间必须同心同德言行一致，六，八，十一月可得财利。",
    "置货": "置货一事，因有神愿未谢，应及早改谢，后置货精心保管， 秋后可得大利。"
  },
  "出外": {
    "出外": "卜出外一事可大胆往前，凡事勿疑于二，三，五月一派好运自有贵人名利成就。"
  },
  "谋望求财": {
    "谋望": "沉迷踪迹未享通，今日承恩谢苍穹，改正前非行大道，自然财禄渐兴隆。",
    "谋望解曰": "谋事前有阻隔，是无先许吓神恩，今欲重谋必先改谢神恩交秋后谋定成之",
    "求财": "正财初时利薄，应求神后无谢神应当天改谢之宜正道经营交六，八，十二月地派兴旺重倍偏财勿取!"
  },
  "学艺功名": {
    "学艺": "卜学艺之卦，宜择吉日进艺门拜良师，勤学苦练定可学得手艺随身。",
    "功名": "功名成就，荣宗耀祖，应谢天地浓恩。"
  },
  "行舟六畜": {
    "行舟": "行舟顺风得利，满载荣归，大吉大利。",
    "六畜": "初时有阻宜谢神，喂养六畜手欲动。休教虚度年月日，可保平安利倍增。",
    "猪羊": "",
    "草龙": "",
    "三鸟": "",
    "田蚕": ""
  },
  "移徙": {
    "移徙": ""
  },
  "行人": {
    "诗": "",
    "解曰": ""
  },
  "婚姻": {
    "婚姻": "前缘配偶是今生，莫为资财重与轻，自有贵人扶持处，手攀丹桂上蟾宫。",
    "解曰": "婚姻是前缘配偶，不要计较资财轻重，自有贵人扶持定能成之"
  },
  "官讼": {
    "官讼": "",
    "解曰": ""
  },
  "失物": {
    "失物": "",
    "解曰": ""
  },
  "占病": {
    "占病": "",
    "解曰": ""
  },
  "其他": {
    "灶君": "",
    "阳基": "",
    "六甲": "",
    "子息": "",
    "祖山": "",
    "青草": ""
  }
}

=== LeoonLiang/xuanwu-fozu-lingqian/data/15.json
{
  "签号": "第十五签",
  "签名": "诸葛亮出身",
  "签文类型": "谋为果决之兆",
  "卦象": "大吉之卦",
  "生肖": "午马",
  "签文简介": {
    "戏文": "诸葛亮隐居隆中躬耕垄亩，而志在天下。刘备从徐庶荐，三顾茅庐。亮感其情直义重，始与之纵论天下形势，陈治世之策，弄出助刘备逐鹿中原，建立蜀国。",
    "诗曰": "一日赴东升，二日水中明;春风和气暖，禄马进门庭。",
    "内兆": "旭日东升"
  },
  "家宅运势": {
    "签文": "保得自家莫取钱，好香烧炷谢苍天，田蚕六畜皆兴旺，受佛今年胜旧年。",
    "解曰": "吉宅人口可得喜气，但防三四月口舌涉财，主事人不义之财勿取宜虔诚当天改谢神恩，请佛祖福灯安吊门上祭化之后居住财丁兴隆也。"
  },
  "岁君签": {
    "总诗": "月满今霄离海边，时人感仰赖青天，清光照耀难星退，君子求谋便得官。",
    "年龄运势": [
      {
        "年龄": "1-3岁",
        "男": "小孩根基足养，八字清秀，旺益上人并茂，三、四月小疾无妨，吉星寿命绵长。",
        "女": "小女根苗足旺，利益上人并茂，夏月虽有小疾无妨，有吉星守命平安。"
      },
      {
        "年龄": "4-7岁",
        "男": "小儿运限叶吉，生性天真活泼，有旺益上人并茂，夏月小疾无妨，吉星守命平安。",
        "女": "小女今年顺遂，伶俐活泼，旺益上人并茂，夏月虽有小疾无妨，出入平安。"
      },
      {
        "年龄": "8-12岁",
        "男": "小童今年上运，各事伶俐，宜入学校读书，定卜进步，三、四月小疾无妨，吉星守命平安。",
        "女": "小女运限顺吉，伶俐活泼，旺益上人并茂，三、四月小疾无妨，吉星守度平安。"
      },
      {
        "年龄": "13-15岁",
        "男": "童造运度亨通，聪明开窍，可入学校读书，定卜进步，前途有望，出入平安。",
        "女": "玉造运度叶吉，各事伶俐，三、四月虽有小皮疾无妨，有吉星照身出入平安。"
      },
      {
        "年龄": "16-17岁",
        "男": "吉星步运亨通，如日东升，各事通情达理，三、四月小疾无妨，吉星守命平安。",
        "女": "美造运度亨通，如月之明，五行清秀，三、四月小疾无妨，吉星守命渐入佳景平安。"
      },
      {
        "年龄": "18-29岁",
        "男": "英造步运亨通，如日东升，做事才能，三、四月虽有小疾无妨，有贵人扶助，可得财喜，且出入平安。",
        "女": "玉造行运交泰，如月之明，五行清秀，四柱安和，助益家门，三、四月小疾无妨，吉星守命平安。"
      },
      {
        "年龄": "30-55岁",
        "男": "乾造步运亨通，如日东升，老练经济，可得财运，但凡事从正向外发展，有贵人扶助出入平安。",
        "女": "坤造行运交泰，如月之明，贤淑智慧，助益家庭，三、四月虽有小疾无妨，有吉星照身平安。"
      },
      {
        "年龄": "56-69岁",
        "男": "台造步运亨通，如日东升，忠诚老练，有财运可得，但凡事宽怀，三、四月小疾无妨，贵人扶助平安。",
        "女": "坤造行运叶吉，各事智慧，可称内助，但勿操迫，暗疾无妨，三、四月守旧，幸吉星守命平安。"
      },
      {
        "年龄": "70岁以上",
        "男": "台造老运安康，老当益壮，有些小疾无妨，福星拱照，晚景胜前平安。",
        "女": "妇造老运交泰，旺益子孙，有些暗疾无妨，有吉星照身，步入佳景平安。"
      }
    ]
  },
  "生意": {
    "生意": "春夏财利虽有亏，明智壮大购货归，收购货物仓中放，秋冬出售利非微。",
    "生意解曰": "生意之卦如龙蛇混杂，恐三,四月有阻隔应谨慎，有贵人扶助五，八，十一月有厚利。",
    "开铺": "上春恐有阻隔小利，候秋冬月生意兴隆，有贵人扶助源广进。",
    "合伙": "大吉有财利可得但防歹人破坏，忍口舌伙计应同心协力经营顺昌也!",
    "置货": "卜置货初有交拼，若有胆量多取，交秋冬时节货物振价，可得厚财大利也。"
  },
  "出外": {
    "出外": "卜出外一事时运当权，谋事应有胆量任其向往，有贵人扶助可卜名利双全!"
  },
  "谋望求财": {
    "谋望": "此身相逢更遇邀，龙蛇天外拔迢迢，平生伴你营随意，云有天梯水有路。",
    "谋望解曰": "谋事定成但有些口些舌无妨,宜立智前进有贵人扶助可得名利双成",
    "求财": "正财取之有得但恐防三，四月阻隔，应果决进前交五，八，十一月有厚利入手，偏财有小人恐有官非破财，到底平安也!"
  },
  "学艺功名": {
    "学艺": "卜学技之卦，为谋为果决之兆，勿三心二意，应一心一意，下决心学习，定得名师传真艺也。",
    "功名": "功名肖龙猴之人定可显达，余者龙猴科中。"
  },
  "行舟六畜": {
    "行舟": "行舟顺风，时运亨通，得利大吉。",
    "六畜": "六畜肥大且平安，虽有小阻心莫慌。祈祷神明来保佑，猪牛羊群只只全。",
    "猪羊": "",
    "草龙": "",
    "三鸟": "",
    "田蚕": ""
  },
  "移徙": {
    "移徙": ""
  },
  "行人": {
    "诗": "",
    "解曰": ""
  },
  "婚姻": {
    "婚姻": "前生注定是姻缘，好貌才郎登对年，要虔事心酬天地，管教夫妻两团圆。",
    "解曰": "前生注定男才女貌俩相配，宜诚心配偶先谢天地，夫妻可得百年皆老"
  },
  "官讼": {
    "官讼": "",
    "解曰": ""
  },
  "失物": {
    "失物": "",
    "解曰": ""
  },
  "占病": {
    "占病": "",
    "解曰": ""
  },
  "其他": {
    "灶君": "",
    "阳基": "",
    "六甲": "",
    "子息": "",
    "祖山": "",
    "青草": ""
  }
}

=== LeoonLiang/xuanwu-fozu-lingqian/data/31.json
{
  "签号": "第三十一签",
  "签名": "打北齐秦家比械",
  "签文类型": "四路虚险之兆",
  "卦象": "下卦",
  "生肖": "寅虎",
  "签文简介": {
    "戏文": "南北朝时周王吞并北齐，下晋阳，攻济南。北齐亲军护卫秦旭，武卫大将军秦彝父子毁家纾难，勤王御敌，均为周行军都总馆杨林杀害，秦家势危，家将秦安帮宁夫人负幼主秦琼突围脱险，逃难路遇程夫人，被收留回家。秦安代行主责，教幼主攻书习武，使秦家锏法得以传于秦琼。",
    "诗曰": "夏月逢天旱，三冬心失收;肥羊遇饿虎，遭遇恐生愁。",
    "内兆": "乌云遮月"
  },
  "家宅运势": {
    "签文": "君家何必惹非灾，南北防七星来?，求祷福神更改吉，不然安得皱眉开。",
    "解曰": "吉宅有七星杀占宅，防三，六，九月灾难口舌失财，火星小心，吓佛祖保平安，请令旗安门上镇宅祭化南北斗星君，居住平安妇人有喜生女勿出外。"
  },
  "岁君签": {
    "总诗": "心事忡忡常不宁，坐得方安又未安，兴意施为全未遂，恰似明月被云迷。",
    "年龄运势": [
      {
        "年龄": "1-3岁",
        "男": "小儿根苗浅薄，惟防上春月灾难波阻，守旧，宜吓月娘化吉方保寿命绵长。",
        "女": "小女根苗虽足，防上春月小疾多事，宜吓月娘化吉守旧方保出入平安。"
      },
      {
        "年龄": "4-7岁",
        "男": "小儿现年运限未美，但嫌执僻，春夏月防小灾疾，吓月娘化吉交秋返运平安。",
        "女": "小女之卦运限未美，哭僻太重，防春夏月灾难，宜吓月娘交秋平安。"
      },
      {
        "年龄": "8-12岁",
        "男": "小童现年运度未美，自执己僻，春夏月小疾波阻，知避暑，吓月娘交秋返运平安。",
        "女": "小女今年运度未遂，春夏月惟防灾难多事，宜知避暑，吓月娘交秋返运平安。"
      },
      {
        "年龄": "13-15岁",
        "男": "小童人虽精通，但防春夏月波灾多疾，吓月娘化吉交秋返运平安。",
        "女": "小女之卦时令未美，春夏月但防灾难多事，守旧并吓月娘化吉交秋平安。"
      },
      {
        "年龄": "16-17岁",
        "男": "祥造现年时令未美，似乌云遮月，虽聪明开窍，但防春夏月小疾多事，吓月娘交秋转运平安。",
        "女": "玉造人虽技巧，但嫌美中不足，似乌云遮月，惟防春夏月多生小疾，宜吓月娘交秋返运平安。"
      },
      {
        "年龄": "18-29岁",
        "男": "英造步运未美，似乌云遮月，但防春夏月灾难口舌小人祸非，戒性，交秋转运贵人扶助平安。",
        "女": "玉造行运未美，似乌云遮月，虽有助益家庭，但防春夏月小疾，口舌吞忍，交秋转运玉体安康。"
      },
      {
        "年龄": "30-55岁",
        "男": "乾造步运似乌云遮月，防春夏月小人不测之祸，凡事从正道，交秋转运贵人扶助平安。",
        "女": "坤造行运虽旺益家庭，但嫌得此挂美中不足，惟防春夏月暗疾口舌，吞忍性气，交秋平安。"
      },
      {
        "年龄": "56-69岁",
        "男": "台造步运不美，签文乌云遮月，惟防春夏月小人嫁祸，闲事切勿近理，交秋转运有贵人扶助平安。",
        "女": "坤造行运未美，虽有旺益家庭，但嫌操心暗疾，宜吞忍口舌，忌看病人，交秋转运平安。"
      },
      {
        "年龄": "70岁以上",
        "男": "福造老运不旺，惟防春夏月灾难跌地之厄，早晚上落下小心，交秋老福安康。",
        "女": "妇造老运不旺，为人多忧多虑，凡事温柔大量，春夏月守旧，上落小心，交秋福体安康。"
      }
    ]
  },
  "生意": {
    "生意": "春夏生意大不祥，正月守分利不偏，祈祷神明力保佑，冬至时节利可添。",
    "生意解曰": "生意如虎上壁财难得，宜守旧业苦力经营秋后可得利，肖牛羊者恐折本招祸",
    "开铺": "卜开铺之卦恐有阻失，肖牛羊者失更大，未开之铺勿开，若是老铺宅应防歹人祸害劫财，宜求佛祖令旗化吉。",
    "合伙": "卜合伙之卦不美如四路虚险之兆，恐伙计有私偏恐惹是非口舌灾难，勿合为要也!",
    "置货": "卜置货恐市情失，无货可取，若有货可取，宜停留至秋冬，可得财利也。"
  },
  "出外": {
    "出外": "卜出外一事四路絮险恐有小人伤害抢劫，宜在家守旧经营则免生愁!"
  },
  "谋望求财": {
    "谋望": "自然心下意忙忙，怎奈他人心自慌，财物如山皆分定，劝君守旧待时光。",
    "谋望解曰": "时令不美谋事难成，肖牛羊之人更不可谋之，定失并防有祸",
    "求财": "正财春夏月跋涉又防阻失，凡事立志经营秋后得利，偏财肖牛羊者勿取，恐吓惹是非受惊!"
  },
  "学艺功名": {
    "学艺": "卜学技艺之卦不美，如乌云盖月之兆，恐学不成，半途而废，寻师学之，便可成功也。",
    "功名": "功名难得，肖牛羊者更免想录取也。"
  },
  "行舟六畜": {
    "行舟": "行舟不吉，仔细行事可以平安也。",
    "六畜": "六畜时运今未通，费尽心机恐成空。借助神力来保佑，交秋月圆才见功。",
    "猪羊": "",
    "草龙": "",
    "三鸟": "",
    "田蚕": ""
  },
  "移徙": {
    "移徙": ""
  },
  "行人": {
    "诗": "",
    "解曰": ""
  },
  "婚姻": {
    "婚姻": "花言巧语岂为真，浪蝶游蜂不可亲，不信但看园内物，一番风雨就伤神。",
    "解曰": "婚姻不成，媒人花言巧语不可信以为真，如浪蝶游蜂不可相亲，若成之恐不长久"
  },
  "官讼": {
    "官讼": "",
    "解曰": ""
  },
  "失物": {
    "失物": "",
    "解曰": ""
  },
  "占病": {
    "占病": "",
    "解曰": ""
  },
  "其他": {
    "灶君": "",
    "阳基": "",
    "六甲": "",
    "子息": "",
    "祖山": "",
    "青草": ""
  }
}

=== LeoonLiang/xuanwu-fozu-lingqian/data/07.json
{
  "签号": "第七签",
  "签名": "韩信得志",
  "签文类型": "暗中有喜之兆",
  "卦象": "中平之卦",
  "生肖": "寅虎",
  "签文简介": {
    "戏文": "韩信少贫，称淮阴饿夫，曾受胯下之辱。后为楚执载郎官，项羽轻之。张良知为帅才，说归汉。刘邦拜为师。韩信主练兵，明修栈道而暗渡陈仓，下三秦直迫中原，戎马五年，扶助刘邦，定鼎西汉。",
    "诗曰": "风起见云生，时享运也通;八龙交会日，方遇宝花缘。",
    "内兆": "枯木逢春"
  },
  "家宅运势": {
    "签文": "淹滞消除正可夸，福神明点照君家，从今莫听闲人说，树正何愁月影斜。",
    "解曰": "吉宅喜气盈门，但防小孩生端祸非而分家，主事人勿听妇女人言，宜从正气公正理，则家道可圆，埕口水道不美要修通，厝前受煞求令旗安门。"
  },
  "岁君签": {
    "总诗": "枯木逢春色欲华，愿交树长发萌芽，时人莫把为柴砍，自待春来又发花。",
    "年龄运势": [
      {
        "年龄": "1-3岁",
        "男": "小儿根基足养，八字清格，旺益上人并茂，夏月小疾无妨，吉星守度寿命绵长。",
        "女": "小女根苗足养，有旺益上人并茂，春夏月虽有效皮恙无妨，吉星守命平安。"
      },
      {
        "年龄": "4-7岁",
        "男": "小儿之卦叶吉，天真活泼，有旺益上人并茂，春夏月虽有小皮疾无妨，吉星守度平安。",
        "女": "小女之卦运度顺遂，各事伶俐，利益上人，春夏月虽有些小疾无妨，吉星照身出入平安。"
      },
      {
        "年龄": "8-12岁",
        "男": "小儿今年运度亨通各事伶俐活泼，可培养入学校读书，定卜进步平安。",
        "女": "小女之卦时运交泰，如枯木逢春，旺益上人，小疾无妨，吉星守度平安。"
      },
      {
        "年龄": "13-15岁",
        "男": "童造现运亨通，聪明开窍，宜入学校读书，远景有望而且出入平安。",
        "女": "小女现年交上美运，各事精通，旺益家门财喜，虽有小疾无妨，出入平安。"
      },
      {
        "年龄": "16-17岁",
        "男": "祥造现年转交好运，如枯木逢春，宜学艺业，卦中有贵人扶助，出入平安。",
        "女": "玉造行运交泰，如枯木逢春，助益家庭，春夏月虽有小疾无妨，吉星守度平安。"
      },
      {
        "年龄": "18-29岁",
        "男": "英造步运亨通，如枯木逢春，做事奇才通能，可向外争取，定卜有贵人扶助，可得财喜平安。",
        "女": "玉造行运交泰，如枯木逢春，各事技巧贤玉，夏月虽有小疾无妨，贵人扶助平安。"
      },
      {
        "年龄": "30-55岁",
        "男": "乾造步运亨通，如枯木逢春，奇才老练，宜向前发展，定卜有贵人扶助，可得财喜，出入平安。",
        "女": "坤造行运交泰，各事贤淑智慧，有内助之称，虽有些暗疾无妨，吉星守命可卜出入平安。"
      },
      {
        "年龄": "56-69岁",
        "男": "台造步运亨通，做事忠诚经济，但勿迫性，有些小疾口舌无妨，卦中贵人扶助，可得财运平安。",
        "女": "坤造行运叶吉，虽旺益家庭，但嫌常时暗疾上身，春夏月守旧，幸吉星守度平安。"
      },
      {
        "年龄": "70岁以上",
        "男": "台造得此卦，如枯木逢春，老当益壮，但三、五、八月上落小心，晚景胜前平安。",
        "女": "妇造行运有旺益子孙，但防暗疾，喜孝物勿食，三、五、八月守旧，可吉也。"
      }
    ]
  },
  "生意": {
    "生意": "春夏生意交易稀，秋冬运开有财利，偏财阻失不可取，正道经营防口舌。",
    "生意解曰": "生意经营时令合局,宜刻苦维持经营交叁，五，八月生意兴隆，有大财利可得。",
    "开铺": "卜开铺之卦应防小人口舌，防人不仁宜请招财得君镇宅，求佛祖令旗安门上祭化平安。",
    "合伙": "卜合伙之卦大吉合之可成，但伙计应同心同德协力经营，有大财利可得!",
    "置货": "置货之卦，初时有高价，此货可发售，若是存放货，价恐败也。"
  },
  "出外": {
    "出外": "卜出外一事，时令当权，凡事勿猜测，大胆前往，有贵人重重，可得成就。"
  },
  "谋望求财": {
    "谋望": "人在山中待好音，君人拨探说知音，如今借得东风力，万里扬帆渐转身。",
    "谋望解曰": "谋事可成但初谋之有小人阻隔,待叁，五八月有贵人扶助，到底可以成功。",
    "求财": "正财库取财除时利薄，宜刻苦经营立功志维持交二，五，十一月有厚利可取，偏财切不可取之，取之定失。"
  },
  "学艺功名": {
    "学艺": "学技艺之卦，但恐不成，宜细心寻师，按年岁配合吉日拜师，耐心学习可成。",
    "功名": "功名前科不中者，此科如枯木逢春定中。"
  },
  "行舟六畜": {
    "行舟": "行舟上春不吉，下春顺风得利也。",
    "六畜": "饲养猪羊欲认真，春夏平平也要勤。待到六秋寒冬月，定有财利报汝心。",
    "猪羊": "猪羊养之，饲料调和，春夏虽有些阻隔，但不必忧烦，可卜底子平安得厚利也。",
    "草龙": "饲养草龙，平安顺利，可旺益家庭，母牛可有产牛仔，宜吓伯公保佑平安。",
    "三鸟": "卜三鸟之卦，春夏恐有小疾，不宜多养，吓伯公保佑，秋后转运，可得财利也。",
    "田蚕": "田蚕早不吉，晚大吉，四季雨水略顺。"
  },
  "移徙": {
    "移徙": "移徙春夏不可移，待七、八月移之大吉。"
  },
  "行人": {
    "诗": "有书喜讯送君知，庭内人情小微微，且待三羊四马日，定然衣锦返回圆。",
    "解曰": "卜此行似枯木逢春，有贵人扶助可得名利双成，交三、五、八月有佳音回家。"
  },
  "婚姻": {
    "婚姻": "几年久坐少人招，今日枯枝长嫩条，自是有缘千里合，无缘对面路迢迢。",
    "解曰": "婚姻成之佳人出在远方，有缘千里能相会，若是近方的恐是对面不相逢。"
  },
  "官讼": {
    "官讼": "新事伤人旧事情，劝君休要逞高能。平生惟慎宪台上，此地从来不可登。",
    "解曰": "官讼可胜，但不可告，应以和为贵，若告之，虽赢输钱。"
  },
  "失物": {
    "失物": "分明失落在篱边、不解追寻旧愿改。万事迟疑三五日，也须来复改依然。",
    "解曰": "失物落在近处，认真迅速寻找，三、五日便可找到，若延迟，恐难找到也。"
  },
  "占病": {
    "占病": "为知不肯念弥陀，有事终思旧愿改。若肯有心从改过、不教善者见南柯。",
    "解曰": "占病只因有旧愿，应速还谢，宜扣许太阳太阴经保平安，四方祭送，不可迟疑。"
  },
  "其他": {
    "灶君": "卜此灶位分金合课，但嫌灶前秽气，应常时修理清净，则烹煮兴隆也。",
    "阳基": "阳基起造有小人口舌，须忍之，并从慎起建或小财补贴老阳居，嫌白虎畔受塞，有利宜修整之则吉也。",
    "六甲": "卜此胎六甲生男，但恐根基浅薄，宜吓天地化吉或拜契神明保养育平安。",
    "子息": "子息之卦，如枯木逢春，莫嫌慢得，将来自有富贵之子，继承香灯，荣宗耀祖。",
    "祖山": "卜贵祖佳城有横龙结穴，但嫌水神散出，白虎畔受路煞冲伤，坐向有利宜修水神归口并填浮白虎畔朝顾，又受兜池唇浮安葬之，则财丁可吉安。",
    "青草": "卜此地横龙结穴，但嫌面前崎岖，葬时宜沉阳立唇，还嫌有口舌是非，宜用财帛补助解决，葬后财丁兴旺也。"
  }
}
