=== LeoonLiang/xuanwu-fozu-lingqian/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "玄武山佛祖灵签",
  "type": "object",
  "additionalProperties": true,
  "properties": {
    "签号": { "type": "string" },
    "签名": { "type": "string" },
    "签文类型": { "type": "string" },
    "卦象": { "type": "string" },
    "生肖": { "type": "string" },
    "签文简介": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "戏文": { "type": "string" },
        "诗曰": { "type": "string" },
        "内兆": { "type": "string" }
      }
    },
    "家宅运势": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "签文": { "type": "string" },
        "解曰": { "type": "string" }
      }
    },
    "岁君签": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "总诗": { "type": "string" },
        "年龄运势": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "年龄": { "type": "string" },
              "男": { "type": "string" },
              "女": { "type": "string" }
            }
          }
        }
      }
    },
    "生意": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "生意": { "type": "string" },
        "生意解曰": { "type": "string" },
        "开铺": { "type": "string" },
        "合伙": { "type": "string" },
        "置货": { "type": "string" }
      }
    },
    "出外": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "出外": { "type": "string" }
      }
    },
    "谋望求财": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "谋望": { "type": "string" },
        "谋望解曰": { "type": "string" },
        "求财": { "type": "string" }
      }
    },
    "学艺功名": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "学艺": { "type": "string" },
        "功名": { "type": "string" }
      }
    },
    "行舟六畜": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "行舟": { "type": "string" },
        "六畜": { "type": "string" },
        "猪羊": { "type": "string" },
        "草龙": { "type": "string" },
        "三鸟": { "type": "string" },
        "田蚕": { "type": "string" }
      }
    },
    "移徙": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "移徙": { "type": "string" }
      }
    },
    "行人": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "诗": { "type": "string" },
        "解曰": { "type": "string" }
      }
    },
    "婚姻": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "婚姻": { "type": "string" },
        "解曰": { "type": "string" }
      }
    },
    "官讼": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "官讼": { "type": "string" },
        "解曰": { "type": "string" }
      }
    },
    "失物": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "失物": { "type": "string" },
        "解曰": { "type": "string" }
      }
    },
    "占病": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "占病": { "type": "string" },
        "解曰": { "type": "string" }
      }
    },
    "其他": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "灶君": { "type": "string" },
        "阳基": { "type": "string" },
        "六甲": { "type": "string" },
        "子息": { "type": "string" },
        "祖山": { "type": "string" },
        "青草": { "type": "string" }
      }
    }
  }
}

=== LeoonLiang/xuanwu-fozu-lingqian/data/20.json
{
  "签号": "第二十签",
  "签名": "曹操下江南",
  "签文类型": "破船下滩之兆",
  "卦象": "下下之卦",
  "生肖": "丑牛",
  "签文简介": {
    "戏文": "曹操百万雄师下江南，刘备从孔明谋，联吴抗曹，拟火攻。蒋干盗书，曹操中周公谨计，杀蔡瑁张允；又中连环计、苦肉计，连船练兵。于是孔明请东风，火烧赤壁，曹军战船被烧，灰飞烟灭，会军败北。",
    "诗曰": "四野无人到，行人路转迷;虎狼吞瞰地，险处更逢危。",
    "内兆": "破船下滩"
  },
  "家宅运势": {
    "签文": "去年只望今年好，今年何缘又不宁，只为旧房多怪异，却教疑忌损人丁。",
    "解曰": "吉宅人口旺者得喜，衰者破防失之灾，是灶君冲门祖山顺，有利应把灶君祖各宜修理合课向佛祖奉经求佛祖保佑合家平安。"
  },
  "岁君签": {
    "总诗": "有船无楫难撑驾，更被飘流向海洋，嗟叹世人系不得，误人如此走东西。",
    "年龄运势": [
      {
        "年龄": "1-3岁",
        "男": "小儿根苗足养，但防正、四、七月灾难波阻，六甲妇勿抱，吓月娘交秋返运平安。",
        "女": "小女根苗浅薄，惟防正、四、七月小疾波阻，吓月娘化吉交秋返运平安。"
      },
      {
        "年龄": "4-7岁",
        "男": "小儿之卦未美，惟防正、四、七月小疾水厄，水边小心，宜吓月娘，交秋返运平安。",
        "女": "小女运限未美，但防灾难水厄，正、四、七月守旧，宜吓月娘，交秋返运平安。"
      },
      {
        "年龄": "8-12岁",
        "男": "童造时运未美，惟防正、四、七月脚痛手疾，宜守旧，吓月娘，交秋返运，出入平安。",
        "女": "小女之卦未美，惟防灾难水厄，逢水边小心，宜吓月娘，交秋返运平安。"
      },
      {
        "年龄": "13-15岁",
        "男": "童造运度未顺遂，惟防正、四、七月小疾水厄，勿执己僻，吓月娘交秋返运平安。",
        "女": "玉造运限美中不足，惟防灾难水厄，各事小心，吓月娘正、四、七月守旧平安。"
      },
      {
        "年龄": "16-17岁",
        "男": "祥造运度不美，似行舟失楫，但防正、四、七月灾难水厄，逢船过游小心，吓妈祖化吉，交秋平安。",
        "女": "玉造时令未美，似行舟失楫，人虽精巧，惟防脚手痛疾，水边小心，吓妈祖化吉交秋平安。"
      },
      {
        "年龄": "18-29岁",
        "男": "英造步运未美，似行黍失楫，人虽通能，但防正、四、七月灾难口舌，戒忍性气，吓妈祖秋后平安。",
        "女": "玉造行运未遂，虽有助益家庭之心，但防灾难口舌，正、四、七月守旧勿远出，吓妈祖交秋转入佳景。"
      },
      {
        "年龄": "30-55岁",
        "男": "乾造老运不美，白虎星占身，但防正、四、七月小人祸非口舌，交人谨慎，吓妈祖化吉交秋转运平安。",
        "女": "坤造行运不美，白虎星占度，嫌内心迫杂，恐有暗疾口舌，正、四、七月守旧，吓妈祖交秋转运平安。"
      },
      {
        "年龄": "56-69岁",
        "男": "台造步运不美，人虽老练，但嫌性迫，多遭灾难口舌，正、四、七月闲事切勿近理，交秋转运大造平安。",
        "女": "坤造行运虽有内助之德，但嫌操心暗疾，正、四、七月守旧，忌看病人，交秋转运玉体安康。"
      },
      {
        "年龄": "70岁以上",
        "男": "妇造老运不旺，惟防正、四、七月灾难跌地之厄，早晚上落小心，忌看病人，守旧平安。",
        "女": "坤造老运不旺，操心暗疾，忌看病人，正、四、七月守旧，夜时勿外出，交秋可卜平安。"
      }
    ]
  },
  "生意": {
    "生意": "正直守份生意经，偏财一点取不能，货物不宜贪心购，留货秋后价会升。",
    "生意解曰": "生意春夏月财利跋涉，宜守旧正直经营，用心刻苦维持，秋后有财利可得",
    "开铺": "卜开铺之卦时运未通宜从正道过旧经营，秋后有发展可得财利也。",
    "合伙": "卜合伙之卦不美勿为宜若合之定被吞没，定是亏本失利并惹起是非。",
    "置货": "置货初时财利跋涉，还防小人累劫，货物必须小心检点，以守旧，秋后可得利。"
  },
  "出外": {
    "出外": "卜出外之卦不吉，有小人无故生端寄祸，且防水危宜守旧经营，则免生愁也!"
  },
  "谋望求财": {
    "谋望": "千谋万计事难成，枉走江山万里程，不如抽身且守耐，不然别月事来惊。",
    "谋望解曰": "谋事难成时运未到，应该守耐之，若要谋之恐有惊阻，失财祸非之危也!",
    "求财": "正财库取利稀少，又防小人负累，宜刻苦维持宜守旧经营，交秋时令有利可得，偏财难得不可取之，若为之定失也!!"
  },
  "学艺功名": {
    "学艺": "卜学技艺之卦，千谋万计事难成，宜在家自习，暂勿从师，候交泰运，拜师学也。",
    "功名": "功名不中，还恐防失财伤身也。"
  },
  "行舟六畜": {
    "行舟": "行舟不吉，不可出港，若要行舟恐凶。",
    "六畜": "六畜有组须切防，托人养之可平安。求神守旧无他事，不然就有苦加离。",
    "猪羊": "",
    "草龙": "",
    "三鸟": "",
    "田蚕": ""
  },
  "移徙": {
    "移徙": ""
  },
  "行人": {
    "诗": "",
    "解曰": ""
  },
  "婚姻": {
    "婚姻": "许了因何又不从，只因年命不相同，莫教勉强心无定，人岂相逢在梦中。",
    "解曰": "婚姻不成虽然曾经相许过，只因年命不同，小人重重若作成也恰似梦中"
  },
  "官讼": {
    "官讼": "",
    "解曰": ""
  },
  "失物": {
    "失物": "",
    "解曰": ""
  },
  "占病": {
    "占病": "",
    "解曰": ""
  },
  "其他": {
    "灶君": "",
    "阳基": "",
    "六甲": "",
    "子息": "",
    "祖山": "",
    "青草": ""
  }
}

=== LeoonLiang/xuanwu-fozu-lingqian/data/08.json
{
  "签号": "第八签",
  "签名": "韩文公冻雪",
  "签文类型": "破船上滩之兆",
  "卦象": "下下之卦",
  "生肖": "丑牛",
  "签文简介": {
    "戏文": "唐韩愈因阻迎佛骨，触怒天颜，被贬潮州府，路过蓝关。遇入雪封冻，几丧生，幸侄韩湘相救助，始免其难。叔侄会于漂江之滨。韩湘劝登仙，韩愈志在家国，谢绝，又因感于世路艰险，乃作诗以宣其悲愤。",
    "诗曰": "水浅孤舟涸，风寒马不前;故人相别去，唱只鹧鸪天。",
    "内兆": "破船上滩"
  },
  "家宅运势": {
    "签文": "不能安分每奔波，惹得家中祸事多，春夏可忧人口病，秋冬又忙损田禾",
    "解曰": "吉宅人口连年灾疾，口舌失财,吓佛祖相保平安，皆因失祀祖上香火应查明奉祀并做过新灶位，埕口水道宜修通，则居住财丁兴旺。"
  },
  "岁君签": {
    "总诗": "因见渔舟上逆滩，渔舟上岸且盘桓，前滩过了为闲事，惟有后滩过更难。",
    "年龄运势": [
      {
        "年龄": "1-3岁",
        "男": "小孩根苗浅薄，但防正、五、九月灾难波阻，六甲妇勿近抱，吓妈祖化吉方保平安。",
        "女": "小女根苗不旺，正、五、九月防风寒灾难，宜守旧，吓月娘改化平安。"
      },
      {
        "年龄": "4-7岁",
        "男": "小儿之卦时令未美，但恐正、五、九月多生灾难波阻，吓妈祖化吉方保平安。",
        "女": "小女之卦未美，防正、五、九月小疾水厄，逢水边小心，吓妈祖化吉平安。"
      },
      {
        "年龄": "8-12岁",
        "男": "小儿运度未美，但防正、五、九月小疾水厄，水边勿近，吓妈祖化吉方保平安。",
        "女": "玉造运度未美，虽活泼，但防正、五、九月小疾水厄，宜守旧，吓月娘改化平安。"
      },
      {
        "年龄": "13-15岁",
        "男": "童造运度未遂，虽聪明开窍，但正、五、九月水边小心，吓妈祖改化方保平安。",
        "女": "玉造运度美中不足，防水厄小疾，二、五、九月池井边小心，吓妈祖化吉平安。"
      },
      {
        "年龄": "16-17岁",
        "男": "祥造步运不美，似破船上滩，惟防正、五、九月小疾水厄，过渡小心，求神明化吉方保平安。",
        "女": "玉造行运美中不足，似破船上滩，虽是技巧，惟防正、五、九月灾疾水厄，吓天地化吉平安。"
      },
      {
        "年龄": "18-29岁",
        "男": "英造步运不美，签文似破船上滩，虽通能，正、五、九月小人口舌是非，凡事戒忍性情，吓妈祖平安。",
        "女": "玉造行运美中不足，似破船上滩，惟防正、五、九月灾疾口舌，凡事吞忍勿执己意，吓妈祖平安。"
      },
      {
        "年龄": "30-55岁",
        "男": "乾造步运不美，似破船上滩，虽有志难伸，正、五、九月小人不测之祸，凡事从正，吓天地化吉保平安。",
        "女": "坤造行运未美，似破船上滩，但防暗疾口舌，凡事吞忍，正、五、九月守旧，吓天地化吉平安。"
      },
      {
        "年龄": "56-69岁",
        "男": "台造步运不美，人虽老练，但防正、五、九月小人起风波，闲事切勿近理，守正业经营，可卜平安。",
        "女": "坤造行运未美，操心暗疾又防口舌多事，凡事吞忍性气，切勿迫性，吓天地化吉平安。"
      },
      {
        "年龄": "70岁以上",
        "男": "台造老运不旺，恐灾难跌地之厄，早晚上落小心，守旧，宽怀大量平安。",
        "女": "妇造老运不旺，恐操心迫杂，暗疾之厄，上落小心，正、五、九月守旧，则吉也。"
      }
    ]
  },
  "生意": {
    "生意": "破船上滩险其中，生意经营有劫凶，来往交易须谨慎，智慧谋取利兴隆。",
    "生意解曰": "生意经营似破船上滩，财利跋涉，防小人阻隔累害，宜谨慎用智悲谋取利。",
    "开铺": "卜开铺之卦不吉恐伙计不同心，有不美之事发生，勿合平安也。",
    "合伙": "卜合伙之卦不吉，恐防伙计不同心，有不美之事发生，勿合平安也。",
    "置货": "卜置货防小人耗动，失败也，若已失过者，可以置之，交秋冬月有财利可得也。"
  },
  "出外": {
    "出外": "出外之卦时令不通恐防小人累害，生端寄祸宜守旧则免生愁。"
  },
  "谋望求财": {
    "谋望": "命里无时莫强求，何须日夜泛渔舟，红鳞已在秋江上，用尽心机不上钩。",
    "谋望解曰": "谋呈要托别人福，春夏谋之不成要待交秋月圆，托人帮助为便可成。",
    "求财": "正财库取利正如镜内之银，看得见取不着，但宜立志气用谋之可得微利，偏财勿取之。"
  },
  "学艺功名": {
    "学艺": "学技艺之卦，因君年命不合时令，运遇未到，且寒窗自习，秋后寻名师学之成也。",
    "功名": "功名只因运未到，不能得中，失也。"
  },
  "行舟六畜": {
    "行舟": "行舟不详，有出难入，待时行之免险也。",
    "六畜": "圈舍饲养猪牛羊，多只阻隔不吉祥。风吹雨打要防失，至切谨记预告言。",
    "猪羊": "猪羊之卦不吉少利，不可贪养，恐防二、五、八月阻失，大只出卖，吓伯公保平安。",
    "草龙": "草龙之卦，恐防疾难之厄，勿贪心使用，应精心饲养，吓伯公保平安。",
    "三鸟": "三鸟之卦，不宜多养，恐防二、五、八月阻失，大只及时出卖，吓伯公保平安。",
    "田蚕": "田蚕早晚二冬少吉怕尾，四季雨水各人福。"
  },
  "移徙": {
    "移徙": "移徙不利，宜守旧待时，渐安旧居也。"
  },
  "行人": {
    "诗": "霸留常挂两头忧，阻隔关山不自由。惆怅凶多怨恨事，更无消息到扬州。",
    "解曰": "行人在外身体健康，但恐小人阻隔，音信稀断，吓妈祖化吉保平安。"
  },
  "婚姻": {
    "婚姻": "旁人只说俩相当，难测胸怀损虎狼，口好不如心内好，不如独枕卧藤床。",
    "解曰": "婚姻不可成就，因为小人语言不够真实，胸怀似虎狼不可相信。"
  },
  "官讼": {
    "官讼": "得知闲处且和闲，扪到人心有恶奸，莫说酒中胡乱语，岂知台上对词难。",
    "解曰": "此讼有败无胜，宜和不宜告，若告之恐受奸害，不可乱说，要抽身不理为吉。"
  },
  "失物": {
    "失物": "为因不慎失马羊，触得心头日夜忧。人眼不如天眼现，分明教尔莫贪谋。",
    "解曰": "失物是贪谋而得来电，因而失之难寻，不得回也，勿乱猜疑人家，免生祸非也。"
  },
  "占病": {
    "占病": "只因小事恼心怀，惹得忧疑杂病来。急向静中求善福，莫教身躯堕尘埃。",
    "解曰": "卜病是由小事操心而引起，应急速静下心来，请良医治疗，向四方祭送大吉。"
  },
  "其他": {
    "灶君": "卜此灶位不美，灶前嫌秽气，宜将灶位退后，做新灶，则烹煮平安大吉。",
    "阳基": "卜阳基龙运不旺，又高低轻重畔，数年败失，宜修整过居住，造新阳基不成有阻，守旧待时吉之。",
    "六甲": "六甲生男，恐防有阻，根基不足，速宜过继或拜契神明保佑，生女宜嫁出。",
    "子息": "子息之卦，比如枝头生一果一果还遭水灾，宜多做善事，求神明保佑，终有麒麟入梦来也。",
    "祖山": "贵祖佳城有结穴，但龙运不旺，水神阳走，坐向有利宜修整龙运并埋水神归口，又掩祭午方煞气之后，财丁兴旺，惟山子分金宜过别地，则子孙平安。",
    "青草": "此地有结穴，但嫌龙运不旺，出水阳走，葬时宜修龙运并理妥水神归口，立唇掩祭午方煞气，葬之则财丁平安也。"
  }
}

=== LeoonLiang/xuanwu-fozu-lingqian/data/48.json
{
  "签号": "第四十八签",
  "签名": "黄野仁遇仙",
  "签文类型": "九转丹成之兆",
  "卦象": "大吉之卦",
  "生肖": "酉鸡",
  "签文简介": {
    "戏文": "黄野仁者，山野之骄子也。日受大自然之引诱，出世之心生而日炽。乃刻意求仙，苦未得。日倦睡，魂游而不意遇仙。仙带回洞中炼丹。经日，九转丹成。黄野仁用之，率未成仙，仙使回家。至家，乡里中人均不相识，问及故人，连老者也不知之。黄野仁始知洞中方一日，世上已千年矣。",
    "诗曰": "五色祥云升，霞光满室明;蛟龙奋疾起，倾刻九里程。",
    "内兆": "金蝉脱壳"
  },
  "家宅运势": {
    "签文": "凶杀已去福神来，忽汝家中大发财，此际管教人物旺，秋冬百事真和谐。",
    "解曰": "凶灾当头春夏人口奔波，疾难是非多，失财是厝前受杀冲伤，宜求佛祖令旗安门上祭化保平安，若有喜凶灾可消除。"
  },
  "岁君签": {
    "总诗": "宝镜新磨复见光，四方照耀任行藏，成名久有根基在，润色增光声播扬。",
    "年龄运势": [
      {
        "年龄": "1-3岁",
        "男": "小孩根苗足养，八字成格，旺益上人并茂，春夏月虽有小疾无妨，出入平安。",
        "女": "小女根基稳固，有旺益上人并茂，春夏月虽有小疾无妨，吉星守命出入平安。"
      },
      {
        "年龄": "4-7岁",
        "男": "小儿之卦时令亨通，旺益上人，但夏月汤火小心，虽有小疾无妨，吉星守命平安。",
        "女": "小女运限顺遂，旺益上人，但防三、五月小疾水厄，逢水边小心，幸吉星守命出入平安。"
      },
      {
        "年龄": "8-12岁",
        "男": "小童现年上运，各事伶俐，宜入学校读书，定卜进步，虽有小疾无妨，出入平安。",
        "女": "小女交上美运，各事活泼，可培养温习文化，三、五月虽有小疾无妨平安。"
      },
      {
        "年龄": "13-15岁",
        "男": "童造之卦运度亨通，聪明开窍，宜入学校读书，定卜进步，高迁之贺出入平安。",
        "女": "玉造现年运度甚佳，伶俐活泼，三、五月小疾无妨，但水边小心，幸吉星守命平安。"
      },
      {
        "年龄": "16-17岁",
        "男": "祥造现年运度亨通，如龙得雨，凡事通能特达，学习手艺，夏月虽有小疾无妨，贵人扶助平安。",
        "女": "玉造行运交泰，如龙得雨，各事贤玉，八字清秀，宜学习文化，夏月虽有小疾无妨，吉星守命平安。"
      },
      {
        "年龄": "18-29岁",
        "男": "英造步运亨通，如龙得雨，做事智慧特达，宜向前争取，有贵人扶助，可得财喜平安。",
        "女": "美造行运佳美，如龙得雨，时令交泰，做事智慧，但勿操迫，夏月虽有小疾无妨平安。"
      },
      {
        "年龄": "30-55岁",
        "男": "乾造步运亨通，如龙得雨，做事才能机智，但勿迫性，有贵人扶助，向外发展，可得财喜平安。",
        "女": "坤造行运交佳，如龙得雨，有内助之贤，但勿操迫，夏月虽有小疾无妨，吉星守度出入平安。"
      },
      {
        "年龄": "56-69岁",
        "男": "台造步运上吉，得此卦如龙得雨，为人心直忠诚，夏月虽有小疾无妨，贵人扶助出入平安。",
        "女": "坤造行运甚美，如龙得雨，贤淑智慧，可称内助，但勿操心迫杂，夏月虽有小疾无妨，玉体安康。"
      },
      {
        "年龄": "70岁以上",
        "男": "福造老运得此卦太旺，但防春夏月灾难交脱，守旧，忌入丧门，底子平安。",
        "女": "慈造老运老当益壮，但防暗疾跌地之厄，上落小心，幸吉星守度晚景胜前。"
      }
    ]
  },
  "生意": {
    "生意": "此卦求问生意经，历时凶险已消清，如今借得东风力，生意兴隆财利升。",
    "生意解曰": "数年苦力财利难得，现岁凶险消除无阻，立冬后有厚利，肖龙之人更有财利",
    "开铺": "卜开铺之卦为九转丹成之兆，老铺数年来波阻已过，今年可得厚财利，新开铺宜用苦力经营，冬月有厚利。",
    "合伙": "卜合伙之卦叶吉为金蝉脱壳之兆，除有波阻，伙计宜同心同德协力经营，秋后有大财利伙计有肖龙者更妙。",
    "置货": "置货初时宜现买现卖，且劳力费神，到底涨价，可得厚财利也。"
  },
  "出外": {
    "出外": "卜出外一事有贵人重重在三，五月出外，但平安而且东成西就，有厚财利可得!"
  },
  "谋望求财": {
    "谋望": "百炼千磨方得醇，几年静坐做闲人，如今借得良工力，富贵相逢白色新。",
    "谋望解曰": "谋事防春月有阻，交秋冬月宜用苦力，自有贵人扶助，凡事定能遂心",
    "求财": "正库取财初时利薄宜加苦力维持于五，九，十一月交运可得利，偏财肖龙之人得之，宜忍口舌!"
  },
  "学艺功名": {
    "学艺": "卜学技艺之卦，为九转丹成之兆，时令合局，但君宜下定决心，勤学苦练，定能学得技艺随身。",
    "功名": "功名不中，是时运不通，捐纳也无中纳。"
  },
  "行舟六畜": {
    "行舟": "行舟先难后易，行之大吉。",
    "六畜": "六畜兴旺人今年，大养鸡犬猪牛羊。灾消福来财喜至，鸡肥猪胖牛马壮。",
    "猪羊": "",
    "草龙": "",
    "三鸟": "",
    "田蚕": ""
  },
  "移徙": {
    "移徙": ""
  },
  "行人": {
    "诗": "",
    "解曰": ""
  },
  "婚姻": {
    "婚姻": "重整衣裳衣色新，相思比做自家人，从来只说人才好，低恐人心又染身。",
    "解曰": "重夫娶之大吉，正配难成，一方有恋一方无心，正如流水无情恋落花"
  },
  "官讼": {
    "官讼": "",
    "解曰": ""
  },
  "失物": {
    "失物": "",
    "解曰": ""
  },
  "占病": {
    "占病": "",
    "解曰": ""
  },
  "其他": {
    "灶君": "",
    "阳基": "",
    "六甲": "",
    "子息": "",
    "祖山": "",
    "青草": ""
  }
}

=== LeoonLiang/xuanwu-fozu-lingqian/data/10.json
{
  "签号": "第十签",
  "签名": "甘罗十二为丞相",
  "签文类型": "虑而即行之兆",
  "卦象": "以为下卦",
  "生肖": "亥猪",
  "签文简介": {
    "戏文": "甘罗幼聪慧，帝喜之，令其祖带甘罗入朝见驾。帝抱置腿上，摸其头而笑曰：真乃丞相头也。其祖父即命甘罗谢恩受封。帝以君无戏言封甘罗为丞相，时年方十二。",
    "诗曰": "哇在井中鸣，无影但闻声;月牢在底下，有影又无形。",
    "内兆": "黄蜂采花"
  },
  "家宅运势": {
    "签文": "今年田蚕半吉祥，夏秋又恐损牛羊，冬深人口宜祷福，更防凶人跳矮墙。",
    "解曰": "吉宅人口虽有喜气，但防夏月,疾难口舌，失财贼厄，肖牛者防生痛疾，吓佛祖保平安，皆因厝前受水冲伤求佛祖令旗安门上祭化则平安。"
  },
  "岁君签": {
    "总诗": "不论平地与山尖，无限风光总被占，采得百花成蜜后，到头辛苦为谁甜。",
    "年龄运势": [
      {
        "年龄": "1-3岁",
        "男": "小孩根苗虽稳固，但防夏秋月灾难波阻，六甲妇勿近抱，吓月娘保平安。",
        "女": "小女根苗浅薄，惟防四、六、八、十二月灾难波阻，宜吓月娘化吉方保平安。"
      },
      {
        "年龄": "4-7岁",
        "男": "小儿运限未美，四、六、八、十二月防灾难，不可登高玩耍，吓天地化吉方保平安。",
        "女": "小女之卦时令未美，防灾疾波阻，四、六、八、十二月守旧，吓天地化吉方保平安。"
      },
      {
        "年龄": "8-12岁",
        "男": "小童现年运度未美，但防四、六、八、十二月脚手痛疾，不可登高，吓天地化吉方保平安。",
        "女": "小女现年运度未美，惟防四、六、八、十二月小疾波阻，守旧，吓天地化吉方保平安。"
      },
      {
        "年龄": "13-15岁",
        "男": "童造现年未美，人虽聪明，但防脚手阻疾，四、六、八、十二月守旧，不可登高，吓天地平安。",
        "女": "玉造现年未美，惟防脚手痛疾，四、六、八、十二月勿登高，守旧，吓天地化吉保平安。"
      },
      {
        "年龄": "16-17岁",
        "男": "吉造运度未遂，似黄蜂采花，虽有才能，但防四、六、八、十二月小疾口舌，勿执僻，吓天地保平安。",
        "女": "玉造运度美中不足，似黄蜂采花，惟防四、六、八、十二月脚手痛疾，夜时勿独行，吓天地化吉平安。"
      },
      {
        "年龄": "18-29岁",
        "男": "英造步运未美，似黄蜂采花，人虽通能，惟防四、六、八、十二月小人口舌，凡事从正，吓天地平安。",
        "女": "坤造行运未美，似黄蜂采花，虽助益家庭，但防四、六、八、十二月小疾口舌，凡事吞忍，吓天地平安。"
      },
      {
        "年龄": "30-55岁",
        "男": "乾造步运不美，似黄蜂采花，防四、六、八、十二月小人祸非，宜戒忍性情，交接谨慎，吓天地化吉平安。",
        "女": "坤造行运不美，人虽贤淑，但防暗疾口舌，凡事吞忍，四、六、八、十二月守旧，并吓天地化吉方保平安。"
      },
      {
        "年龄": "56-69岁",
        "男": "台造步运未美，似黄蜂采花，虽是老练，但防四、六、八、十二月不测之祸，闲事勿理，吓天地平安。",
        "女": "坤造行运未美，操心暗疾，凡事吞忍，四、六、八、十二月守旧，夜时勿运出，吓天地化吉保平安。"
      },
      {
        "年龄": "70岁以上",
        "男": "台造老运不旺，人虽忠诚，但防灾疾跌地之厄，六、八、十二月上落小心，勿登高，守旧则吉。",
        "女": "妇造老运不旺，虽有旺益子孙，但防暗疾风气，四、六、八、十二月喜孝物勿食，守旧则吉。"
      }
    ]
  },
  "生意": {
    "生意": "今年生意欲认真，慎防盗贼劫财金，夏月莫挂人家账，秋到求财天有心。",
    "生意解曰": "生意虽有财利可得，但恐小人,劫货，交易宜谨慎见利取利，则财利吉也。",
    "开铺": "卜开铺之卦应防盗贼之厄应防小人诱劫财物，铺门有煞，宜请佛祖符令安门上保平安。",
    "合伙": "不成三人四窍伙计不同心，财物恐有走漏，勿合为宜，合之有祸无利也。",
    "置货": "置货恐防小人耗动，交易要认真谨慎，银项必须亲自点交，有小财利可得。"
  },
  "出外": {
    "出外": "卜出外之卦一事要有胆气坚定前往于二，四月有贵人扶助可得名利双全。"
  },
  "谋望求财": {
    "谋望": "托人去干心中事，口好如何心不好，早早回头归故里，痴只常惯受灾残。",
    "谋望解曰": "卜谋事须防歹人阻隔拐骗或抢劫财帛，宜谨慎应防人不仁勿往外谋之。",
    "求财": "正财库取财虽有得，但恐防小人负累，勿信直中直，须防仁不仁，宜从正道经营，偏财失之不可取，肖牛,羊者失更大。"
  },
  "学艺功名": {
    "学艺": "卜学技艺之卦，因时运未至，学而无成，勿枉费工本，自己学习待时机学之。",
    "功名": "功名不中，勿取吉，肖牛羊者切勿取进。"
  },
  "行舟六畜": {
    "行舟": "行舟凶险，切勿行之，守之平安。",
    "六畜": "夏秋凶险损牛羊，任你求神无应天。肥猪还需防盗贼，不如闲手度虚年。",
    "猪羊": "饲养猪羊有失无得，恐防六、九、十二月阻隔，中大只肥猪要及时出卖，吓伯公保平安。",
    "草龙": "草龙之卦，恐防六、九、十二月阻疾，又防盗厄，宜吓伯公保佑平安，如未养者，渐勿购也。",
    "三鸟": "饲养三鸟，恐防六、九、十二月疾病，又防盗厄，三四只可养，多则不得也。",
    "田蚕": "田蚕中平，防损失，四季雨水不吉。"
  },
  "移徙": {
    "移徙": "移徙应防不吉，因地基有灾险也。"
  },
  "行人": {
    "诗": "艰难跋涉万重山，心事茫茫意未还。又恐路途中人毒，凡事凶险在其间。",
    "解曰": "行人在外凶险事多，恐防小人阻隔祸害，回之艰难，宜吓佛祖保佑身体健康。"
  },
  "婚姻": {
    "婚姻": "野草闲花迷更乱，一朝乐极更生悲，虑心直待姻缘到，莫听旁人说是非。",
    "解曰": "不可轻信媒人话，是闲花野草也切不可取之，若取之欢乐一时有祸也。"
  },
  "官讼": {
    "官讼": "世间难成是贪痴，身为螳螂不见机。只想鸣蝉遭汝捕，不知黄雀在后治。",
    "解曰": "官讼要以和为贵，若告之，起初胜，后定败，因为对方有旁人协助支持。"
  },
  "失物": {
    "失物": "失了财宝莫怨天，谁知贤者更为贤。眼见此物入盗手，只在芦花浅水边。",
    "解曰": "失物已入盗贼之手，纵然到处寻找也难寻见，宜细心观察了解或可见踪迹。"
  },
  "占病": {
    "占病": "恶病缠身无奈何，只防沉重见阎罗。如今若要凶星退，速请僧人念弥陀。",
    "解曰": "求神请良医治疗好也，但肖牛羊之人恶症缠身，求佛祖吓送太阳太阴经平安。"
  },
  "其他": {
    "灶君": "卜此灶位不美，灶前迫塞，宜重新做新灶，烹煮兴隆，财丁兴旺也。",
    "阳基": "卜阳宅生蚁，宜立白雄鸡掩祭化吉，欲起新阳宅有阻口舌，需小财利补办，旧阳宅丑未受煞。",
    "六甲": "卜此胎六甲生女安，生男恐防有阻，根基浅薄，宜过拜契神明保平安。",
    "子息": "前恐难得子，得者也少养，宜多行善事，后来自由子孙继承，平安吉祥也。",
    "祖山": "贵祖佳城横龙结穴，但龙运不旺，丑未分金受煞冲伤，坐向有利宜修龙运壮旺并掩祭丑未方煞气，又理水字配合分明，葬之财丁兴旺也。",
    "青草": "此地横龙有结穴，但嫌龙运不旺，应请有福先生做之财丁兴旺，但丑未分金山头勿取，因水字不美，财丁要破失。"
  }
}

=== LeoonLiang/xuanwu-fozu-lingqian/data/32.json
{
  "签号": "第三十二签",
  "签名": "袁术称帝",
  "签文类型": "日落斜西之兆",
  "卦象": "以为下卦",
  "生肖": "丑牛",
  "签文简介": {
    "戏文": "东汉末年，十八诸侯攻董卓，孙坚得传国玉玺，传于子孙策。尔后孙策为收复江东，将玉玺向袁术换取精兵三千。袁术得玉玺，顿生野心，于淮南称帝。妄图号令天下。曹操会吕布、刘备三雄讨袁，大败袁军。袁术犯天下恶，被困迫吐血，自取灭亡于江亭。",
    "诗曰": "鹤在笼中内，鱼游于釜中;梨花开带雨，金菊吐无花。",
    "内兆": "众星侵月"
  },
  "家宅运势": {
    "签文": "阴人灾害事如何，只为家中惹鬼多，如今要保平安日，除非寻僧礼达摩。",
    "解曰": "吉宅人口防夏月有疾难祸非失财，是埕口水道不美，内有阴人作动又嫌祖山不顺，有利各要修整清楚向佛祖奉经请达摩祖师福灯安门平安。"
  },
  "岁君签": {
    "总诗": "众星侵月也当防，小口阴人起祸殃，弱也之时休改革，预先借福谢苍穹。",
    "年龄运势": [
      {
        "年龄": "1-3岁",
        "男": "小孩根苗足养，八字成格，有旺益上人并茂，春夏月灾难波阻，吓天地化吉平安。",
        "女": "小女根苗虽足，惟防三、六、九月灾难波阻，宜吓天地化吉，方保寿命绵长平安。"
      },
      {
        "年龄": "4-7岁",
        "男": "小儿之卦未美，似恶星占度，但防三、六、九月小疾多事，宜守旧吓天地化吉方保平安。",
        "女": "小女运限未美，虽有旺益上人，但防三、六、九月灾难波阻，吓天地化吉方保平安。"
      },
      {
        "年龄": "8-12岁",
        "男": "小童现年运度未美，虽伶俐，但防三、六、九月多生灾疾之厄，守旧，吓天地化吉方保平安。",
        "女": "小女现年运度美中不足，惟防三、六、九月灾难波阻，夜勿外出，吓天地化吉方保平安。"
      },
      {
        "年龄": "13-15岁",
        "男": "童造今年运度未遂，虽聪明，但防三、六、九月小疾波灾，吓天地化吉方保平安。",
        "女": "小女现年运度未佳，但防三、六、九月灾疾之厄，夜勿远出，吓天地化吉平安。"
      },
      {
        "年龄": "16-17岁",
        "男": "祥造步运不佳，似花开遭雨，虽通能，但防三、六、九月小人口舌，勿在外惹祸，吓天地化吉方保平安。",
        "女": "玉造行运美中不足，似花开遭雨，虽有助益家庭，但防三、六、九月小疾多灾，守旧，吓天地化吉平安。"
      },
      {
        "年龄": "18-29岁",
        "男": "英造步运未美，人虽才能，但防三、六、九月小人口舌祸非，凡事切勿冲动，吓天地化吉方保平安。",
        "女": "玉造行运得此卦，人虽贤玉，但嫌美中不足，三、六、九月灾难口舌，凡事吞忍，吓天地化吉玉体安康。"
      },
      {
        "年龄": "30-55岁",
        "男": "乾造步运不美，人虽老练，但防三、六、九月歹人嫁祸生非，凡事戒忍性气，吓天地化吉方保平安。",
        "女": "坤造行运不美，人虽贤惠，但防暗疾口舌，凡事吞忍性气，吓天地化吉保平安。"
      },
      {
        "年龄": "56-69岁",
        "男": "台造步运未美，人虽忠诚，但嫌时令未美，惟防三、六、九月歹人不测之祸，平地风波，守旧，底子平安。",
        "女": "坤造行运美中不足，似花开遭雨，惟防暗疾口舌，凡事吞忍性气，守旧底子平安。"
      },
      {
        "年龄": "70岁以上",
        "男": "吉造老运不旺，似花开遭雨，惟防灾难跌地之厄，早晚上落小心，喜孝堂勿进，守旧底子平安。",
        "女": "妇造老运不旺，似花开遭雨，惟防暗疾上身，忌看病人，三、六、九月守旧，底子旺益子孙平安。"
      }
    ]
  },
  "生意": {
    "生意": "守旧经营可平安，小人劫财要提防，百事用心要谨慎，结果只能小利攀。",
    "生意解曰": "生意不贪心妄作，要仍按旧业经营防偷劫，货款出入谨慎用心窍取利也",
    "开铺": "卜开铺之卦不美未开者开勿，已开者必守旧经营勿贪财妄取，防小人防亏本，请佛祖符令镇宅平安。",
    "合伙": "卜合伙之卦似众星侵月之兆，伙计有私心，防小人防亏本，勿合则吉也!",
    "置货": "卜置货初时有阻隔，但要用心窍，后来可得财利也。"
  },
  "出外": {
    "出外": "卜出外一事时令不通，恐吓防小人劫劫财，勿出外宜守旧经营则可安然!"
  },
  "谋望求财": {
    "谋望": "古来名利与兵机，谋望虽多得者稀，若不将心且忍耐，必然失计被人欺。",
    "谋望解曰": "谋事有小人累害有口舌，防祸非失财宜用心窍，用些财帛帮助事可成",
    "求财": "正财利小稀薄防小人耗劫恐要亏本，宜谨慎从正道，偏财阻失不可取，取必失之!"
  },
  "学艺功名": {
    "学艺": "卜学技艺之卦，似众星侵月之兆，恐有小人祸害，恐惹是非，学之难成，宜候时运才学之。",
    "功名": "功名不中，还恐惹祸破财也。"
  },
  "行舟六畜": {
    "行舟": "行舟中平，但恐防有盗贼也。",
    "六畜": "今年六畜难经营，鸡犬无端怪魔王。猪牛羊鹅也有阻，后悔莫及不可行。",
    "猪羊": "",
    "草龙": "",
    "三鸟": "",
    "田蚕": ""
  },
  "移徙": {
    "移徙": ""
  },
  "行人": {
    "诗": "",
    "解曰": ""
  },
  "婚姻": {
    "婚姻": "本来婚偶待团圆，怎奈旁人起祸端，若要事成须速早，不然迟慢守寒年。",
    "解曰": "婚姻切切不可拖延，应及早下聘迎娶，若迟延恐失也，今后又恐无妇也"
  },
  "官讼": {
    "官讼": "",
    "解曰": ""
  },
  "失物": {
    "失物": "",
    "解曰": ""
  },
  "占病": {
    "占病": "",
    "解曰": ""
  },
  "其他": {
    "灶君": "",
    "阳基": "",
    "六甲": "",
    "子息": "",
    "祖山": "",
    "青草": ""
  }
}

=== LeoonLiang/xuanwu-fozu-lingqian/data/16.json
{
  "签号": "第十六签",
  "签名": "关公带嫂秉烛待旦",
  "签文类型": "重囚望赦之兆",
  "卦象": "下下之卦",
  "生肖": "巳蛇",
  "签文简介": {
    "戏文": "关羽被曹兵围困土山，为救嫂计，约三事，降汉不降曹。赴许昌途中，夜歇驿馆，曹操欲乱其君臣之礼，使关公与二嫂同处一室，关公乃秉烛立于户外，达旦无倦色。曹操见关公忠义至此，益重之。",
    "诗曰": "秉烛对佳人，风吹烛泪垂;且防猪与犬，恐惹闲中非。",
    "内兆": "浊油点灯"
  },
  "家宅运势": {
    "签文": "只因不肯敬神明，惹得家中事不宁，今岁若除灾与难，除非重整久家声。",
    "解曰": "吉宅人口可得喜气，但防四, 九，十月祸非疾难失财，肖猪狗之人恐惹祸非，宜安份守已，向佛祖奉经拜祖上香灯，做过新灶居住财丁兴旺兴。"
  },
  "岁君签": {
    "总诗": "浊油点灯灯自灭，方才剔起又垂微，长心烧书空劳力，何不将身忙自归。",
    "年龄运势": [
      {
        "年龄": "1-3岁",
        "男": "小孩根苗虽旺，但防四、六、九、十月灾难波阻，六甲妇勿近，向佛祖添油化吉平安。",
        "女": "小女根基浅薄，惟防四、六、九、十月小疾波阻，吓佛祖化吉方保平安。"
      },
      {
        "年龄": "4-7岁",
        "男": "小儿之卦运限未美，但防四、六、九、十月小疾汤火之厄，向佛祖添油化吉平安。",
        "女": "小女现年运限未美，惟防灾难波阻，四、六、九、十月守旧，向佛祖添油化吉平安。"
      },
      {
        "年龄": "8-12岁",
        "男": "童造运度现年时令未美，防波阻之厄，四、六、九、十月守旧，吓佛祖化吉平安。",
        "女": "小女现年运限未美，四、六、九、十月防有小难灾疾，守旧，吓佛祖化吉平安。"
      },
      {
        "年龄": "13-15岁",
        "男": "童造运度未美，虽聪明，但防四、六、九、十月灾难之厄，宜向佛祖添油化吉平安。",
        "女": "玉造运度美中不足，惟防六、九、十月多生波阻水厄，向佛祖添油化吉平安。"
      },
      {
        "年龄": "16-17岁",
        "男": "祥造步运未美，四、六、九、十月恐有小疾口舌，守旧，勿远出，吓佛祖化吉平安。",
        "女": "玉造美中不足，虽技巧，但防四、六、九、十月多事，夜时勿外出，吓月娘化吉平安。"
      },
      {
        "年龄": "18-29岁",
        "男": "英造步运不美，似浊油点灯，惟防六、九、十月小疾口舌，凡事戒忍，向佛祖添油化吉方保平安。",
        "女": "玉造行运不佳，似浊油点灯，人虽贤玉，但防小疾波阻，四、六、九、月夜时勿远出，向佛祖添油平安。"
      },
      {
        "年龄": "30-55岁",
        "男": "英造步运不美，似浊油点灯，人虽老练，但防六、九、十月不测之祸，宜从正不可冲动，吓天地化吉平安。",
        "女": "坤造行运美中不足，人虽贤淑，但嫌操心迫杂，暗疾口舌，六、九、十月吞忍性气，吓老爷化吉方保平安。"
      },
      {
        "年龄": "56-69岁",
        "男": "台造步运不美，虽老练，但防四、六、九、十月灾难口舌，凡事戒忍性情，闲事切勿近理，底子平安。",
        "女": "坤造行运未美，操心暗疾，凡事吞忍，四、六、九、十月守旧，夜时切勿外出，宜静养，底子平安。"
      },
      {
        "年龄": "70岁以上",
        "男": "福造老运不旺，可比风中点烛，惟防六、九、十月灾难跌地之厄，早晚上落小心，守旧则大吉平安。",
        "女": "坤造老运美中不足，操心劳烦暗疾上身，四、六、九、十月守旧，忌看病人，喜孝物勿近则平安。"
      }
    ]
  },
  "生意": {
    "生意": "何必次次费心机，用尽苦力财力稀，口舌欲任偏财勿，正财守旧能得利。",
    "生意解曰": "生意似穿破鞋过水，防小人耗财，与人交易信直中直，宜苦力不从经营可得财力",
    "开铺": "卜开铺之卦为浊油点灯，恐防大火是非口舌，小人耗财宜过旧经营平安也。",
    "合伙": "卜合伙之卦不吉伙计多心，恐防是非口舌，亏本切勿合，合之定失!",
    "置货": "卜现年置货小利，宜用苦心经营，恐防口舌是非，不可贪财利则吉。"
  },
  "出外": {
    "出外": "卜出外一事因时令不美，恐防小人生端，宜守旧经营方保无忧!"
  },
  "谋望求财": {
    "谋望": "覆危渡水两头难，万计千磨财利艰，守份安贫宜忍耐，忙忙劳力不如闲。",
    "谋望解曰": "谋事不成如破鞋覆渡水，艰难重重防歹人祸害，九，十月更应谨慎防备",
    "求财": "正财库利小九，十月有歹徒负累，宜稳重谨慎经营，见利取利得之安，偏财定失，分文勿取也!"
  },
  "学艺功名": {
    "学艺": "卜学技艺之卦不美，恐君主意不定，三心二意，半途而废，一无所成也。",
    "功名": "功名不中，肖猪者若进场，恐不吉有失。"
  },
  "行舟六畜": {
    "行舟": "行舟不顺，切不可行，守旧平安。",
    "六畜": "今年六畜财利疏，不可贪心想养多。阻隔须吓伯公去，保佑平安灾祸无。",
    "猪羊": "",
    "草龙": "",
    "三鸟": "",
    "田蚕": ""
  },
  "移徙": {
    "移徙": ""
  },
  "行人": {
    "诗": "",
    "解曰": ""
  },
  "婚姻": {
    "婚姻": "方才说起惹忧愁，想是姻缘不到头，如今若得言相许，又恐吓旁人暗里谣。",
    "解曰": "婚姻不成有小人重重，纵然成之恐不长久，也许被歹徒占有"
  },
  "官讼": {
    "官讼": "",
    "解曰": ""
  },
  "失物": {
    "失物": "",
    "解曰": ""
  },
  "占病": {
    "占病": "",
    "解曰": ""
  },
  "其他": {
    "灶君": "",
    "阳基": "",
    "六甲": "",
    "子息": "",
    "祖山": "",
    "青草": ""
  }
}

=== LeoonLiang/xuanwu-fozu-lingqian/data/05.json
{
  "签号": "第五签",
  "签名": "苏东坡游江",
  "签文类型": "心动意和之兆",
  "卦象": "大吉之卦",
  "生肖": "辰龙",
  "签文简介": {
    "戏文": "宋苏东坡与佛印善同游河，遇渔翁父女，邀过船饮，苏与佛印吟诗索对，渔翁欲唱和，两人自恃博学精思，笑置之。不料渔女精思敏捷，每求对，辄暗示其父，遂难倒苏学士，使苏两人作山外山之叹。",
    "诗曰": "威武逞英雄，时享运也通;鹿行方见马，遇贵喜重重。",
    "内兆": "顺水行舟"
  },
  "家宅运势": {
    "签文": "门庭兴旺福神多，人虽无灾百事和，春夏宜防官灾疾，秋冬财物满庭稼。",
    "解曰": "喜气盈门，但防春夏月小疾,及火星之厄，早晚火烛小心，是厝内土神愿和久年香火神恩过旺宜安谢土地神恩则财丁昌盛。"
  },
  "岁君签": {
    "总诗": "舟行风顺去无虑，利涉江湖正遇时，万里程途只可到，所谋遂意事如期。",
    "年龄运势": [
      {
        "年龄": "1-3岁",
        "男": "小儿根基足养，八字清秀，有旺益上人并茂，夏月小疾无妨平安。",
        "女": "小女根苗足养，旺益上人并茂，夏月小疾无妨，定卜出入平安。"
      },
      {
        "年龄": "4-7岁",
        "男": "小儿运限叶吉，天真活泼，水边小心，幸有吉星照身，出入平安。",
        "女": "小女之卦顺遂，有旺益上人并茂，虽有些小疾无妨，出入平安。"
      },
      {
        "年龄": "8-12岁",
        "男": "小儿现年上运，各事聪明开窍，宜入学校读书，定卜进步，出入平安。",
        "女": "玉造现年交上美运，旺益家门，虽有小疾无妨，吉星照身平安。"
      },
      {
        "年龄": "13-15岁",
        "男": "童造运度亨通，聪明特达，培养入学校读书，前途有望，出入拍平安。",
        "女": "玉造运度顺遂，技巧伶俐，夏月小疾无妨，吉星守命，出入平安。"
      },
      {
        "年龄": "16-17岁",
        "男": "祥造步运亨通，做事通能特达，学习文化，远景有希望，出入平安。",
        "女": "玉造行运交泰，如顺水行舟，助益家门财喜，小疾无妨，出入平安。"
      },
      {
        "年龄": "18-29岁",
        "男": "英造步运亨通，如顺水行舟，奇才特达，但勿迫性，贵人扶助，可得财喜，出入平安。",
        "女": "玉造行运交泰，各事技巧贤淑，夏月虽有小疾无妨，卦中有吉星守度平安。"
      },
      {
        "年龄": "30-55岁",
        "男": "乾造步运亨通，如顺水行舟，奇才通能，可向外发展，有贵人扶助，可得财喜，出入平安。",
        "女": "坤造行运交泰，各事贤淑智慧，旺益家门财喜，虽有暗疾无妨，吉星守合平安。"
      },
      {
        "年龄": "56-69岁",
        "男": "台造步运亨通，如顺水行舟，老练忠诚，虽有小疾无妨，贵人扶助，出入平安。",
        "女": "坤造行运交泰，如顺水行舟，贤淑智慧，暗疾无妨，吉星守命平安。"
      },
      {
        "年龄": "70岁以上",
        "男": "台造老运亨通，老当益壮，有些灾疾无妨，贵人扶助平安。",
        "女": "妇造老运交泰，如顺水行舟，虽有暗疾无妨，吉星照身，晚景胜前平安。"
      }
    ]
  },
  "生意": {
    "生意": "生意兴隆财利开，河有桥来天有阶，五洲四海皆可往，有勇有智有厚利。",
    "生意解曰": "卜生意道路四通八达，与人交易不可乱猜，宜立智，五，八，十一月可得厚财利。",
    "开铺": "卜开铺之卦叶吉但交易宜谨慎，应防人不仁，有贵人扶助财利兴隆。",
    "合伙": "卜合伙之卦叶吉合之可成，但伙计应同心同德协力经营，有大财利可得。",
    "置货": "卜置货者宜占前，不可乱疑，须立胆智置而存之，五、八、十一月有利可得也。"
  },
  "出外": {
    "出外": "卜出外一事时令当权，凡事勿猜测，大胆前往有贵人重重可得成就。"
  },
  "谋望求财": {
    "谋望": "欲求动止莫怀疑，名利相寻勿待迟，但得便中须速起，休教叹过运中时。",
    "谋望解曰": "做事内心不要乱怀疑要有胆智,灵活谋之交秋后有贵人扶助定可成功。",
    "求财": "正财库取利宜立智经宜,创举宜占先有贵人扶助可得厚财利，偏财取之恐有失，宜和人家合伙移他人之福也。"
  },
  "学艺功名": {
    "学艺": "卜学艺之卦，与君年命合局，但应忍口舌，刻苦学习，有贵人扶助，定能手艺随身。",
    "功名": "功名准得，武者更为荣贵，营伍可升。"
  },
  "行舟六畜": {
    "行舟": "行舟初时不吉，到底可顺风得也。",
    "六畜": "猪肥牛壮兴旺期，快速饲养莫延迟。天定财利合道理，大投资金收大利。",
    "猪羊": "卜饲养猪羊，饲料调和，可大胆多养，平安顺利，大落资本便可得到大利。",
    "草龙": "饲养草龙水草调和，养之顺利，可旺益家庭，有利可得也。",
    "三鸟": "饲养鸡鹅鸭，大吉顺利，可投资金，大胆多养，各事宜精心管理，有财利也。",
    "田蚕": "田蚕早晚冬大吉，四季风调雨顺也。"
  },
  "移徙": {
    "移徙": "移徙大吉，速速可移，新宅可居之。"
  },
  "行人": {
    "诗": "归期眼望恨悠悠，争奈淹留不自由。若得福神添力佑，轻帆风送即登舟。",
    "解曰": "行人去后无音信者，是因途中有小疾，吓佛祖保平安，有贵人扶助，五、八月有佳音。"
  },
  "婚姻": {
    "婚姻": "婚姻到日不须寻，何必区区枉用心，两边相许无他事，正好乘时射雀屏。",
    "解曰": "婚姻成就百说百合，小登科已到在吉顺也，要借此时运托人说亲也。"
  },
  "官讼": {
    "官讼": "理直何须问上真，纵经官府不受刑。虽然目下多惶恐，定保平安理直伸。",
    "解曰": "官讼得理，无须忧疑，不用烦恐，定能伸张得理，但和之更妙，大吉平安。"
  },
  "失物": {
    "失物": "昨日偏舟过洞庭，知君心上不安宁。虽然失却凡间物，终有还珠且莫惊。",
    "解曰": "东西虽已失去，自然有贵人告诉知音，如数归回，君心上不必忧烦也。"
  },
  "占病": {
    "占病": "谁觉追来疾似风，巫医扁鹊枉施工。但望福神来保佑，病魔退却不相逢。",
    "解曰": "占病者阴邪交缠，宜许吓土神，向四方祭送，请良医治之，病可治愈。"
  },
  "其他": {
    "灶君": "卜此灶位分金合于八宅之课，但嫌灶前秽气，常时宜修理清净，则烹煮叶吉也。",
    "阳基": "卜阳宅欲起造吉，但嫌有些口舌宜忍可成，旧阳宅如坐南向北分金防白虎畔石煞及凶，有利修整则平安。",
    "六甲": "此胎六甲定生男儿，平安也，若产妇相马者定生双胎男儿，吓佛祖天地平安。",
    "子息": "子息之卦初时多花少果，宜为世人多做善事，日后定有贵子可得。",
    "祖山": "卜贵祖佳城横龙结穴，气脉足旺，但嫌白穴低，坐向有利宜修高三五尺，沉阳做又消纳白虎畔相朝之后才兴旺。",
    "青草": "卜此地横龙结穴，气脉足旺，但葬时须将穴位点高三五尺，沉阳做，清掩白虎畔，使之相朝，则葬后财丁兴旺。"
  }
}

=== LeoonLiang/xuanwu-fozu-lingqian/data/29.json
{
  "签号": "第二十九签",
  "签名": "郭子仪拜寿",
  "签文类型": "春来花发之兆",
  "卦象": "上上之卦",
  "生肖": "辰龙",
  "签文简介": {
    "戏文": "唐郭子仪战功显赫，后又平定安史之乱，以年事高解封王，享厚禄而名潢天下，又适逢八十大寿，七子八婿登堂拜寿，满朝文武入府祝遐，连日喜庆，朝野称贺，热闹非凡。古今辅天地、关家国而得功成名就，福禄寿全者至于斯而已也。",
    "诗曰": "新荷初出来，花叶正发开;鬼抱心中斗，名传天下知。",
    "内兆": "花木逢春"
  },
  "家宅运势": {
    "签文": "敬神自是合天心，人善神饮祸不侵，此不淹留无阻滞，田蚕十倍在深秋。",
    "解曰": "吉宅喜气临门田蚕十倍，但嫌夏月人口有小疾口舌涉财，每逢塑望应诚心敬拜佛祖，天地保平安，埕口水道秽修通。"
  },
  "岁君签": {
    "总诗": "阴阳相合事亨通，如今行在明月中，琴瑟调各门户吉，荣华富贵喜重重。",
    "年龄运势": [
      {
        "年龄": "1-3岁",
        "男": "小孩根苗足养，八字清秀，有旺益上人并茂，上春月虽有小疾无妨，吉星守命平安。",
        "女": "小女根基足养，有旺益上人并茂，上春月虽有小疾无妨，吉星守命出入平安。"
      },
      {
        "年龄": "4-7岁",
        "男": "小儿现年运限顺遂，利益上人，上春月小疾无妨，水边小心，吉星守命出入平安。",
        "女": "小女现年运限叶吉，旺益上人，上春月皮疾无妨，水边小心，吉星守命出入平安。"
      },
      {
        "年龄": "8-12岁",
        "男": "小童之卦时令亨通，天真伶俐，培养入学书，定卜进步，吉星照身出入平安。",
        "女": "小女运度叶吉，各事活泼，上春月水边勿近，虽有小疾无妨，吉星守度出入平安。"
      },
      {
        "年龄": "13-15岁",
        "男": "童造现年时令甚佳，各事开窍聪明，勤奋学习文化，定卜进展，出入平安。",
        "女": "小女运度交佳，凡事伶俐精通，但水边小心，上春月虽有小疾无妨，出入平安。"
      },
      {
        "年龄": "16-17岁",
        "男": "祥造运度亨通，如春来花发，做事聪明有智，不可忽视文化，将来有进展之日，出入平安。",
        "女": "玉造行运交泰，如春来花发，凡事技巧，八字清秀，多学艺业，虽有小疾无妨，出入平安。"
      },
      {
        "年龄": "18-29岁",
        "男": "英造步运亨通，如春来花发，做事通能特达，可向外发展经营，有贵人扶助，可得财喜平安。",
        "女": "坤造运度顺遂，如春来花发，智慧贤玉，助益家庭，上春月虽有小疾无妨，出入平安。"
      },
      {
        "年龄": "30-55岁",
        "男": "乾造步运顺吉，如春来花发，来练奇才，宜立凌云壮志，发展前途有贵人扶助，可得财喜平安。",
        "女": "坤造行运交泰，如春来花发，做事智慧，但勿操迫，有些暗疾无妨，吞忍性气，吉星守命平安。"
      },
      {
        "年龄": "56-69岁",
        "男": "台造步运亨通，为人老练忠诚，签文如春来花发，上春月虽有小疾无妨，贵人扶助出入平安。",
        "女": "坤造行运交泰，贤淑温柔，旺益家门，但有些暗疾无妨，卦中有吉星照身，可卜出入平安。"
      },
      {
        "年龄": "70岁以上",
        "男": "福造老运安康，如春来花发，老当益壮，为人宽宏大，定卜晚景胜前平安。",
        "女": "妇造老运康泰，有旺益子孙，有些暗疾无至大害，太阴星守度平安。"
      }
    ]
  },
  "生意": {
    "生意": "山荼荷花不合丘，初时磨苦小利酬，和气待人心头记，硕果遍地大丰收。",
    "生意解曰": "生意合伙不利有阻失，独做二，三磨苦小利，交五，八，十一月生意兴隆可得大利",
    "开铺": "卜开铺之卦如春来花发之兆，生意兴隆可独占鳌头，五月起可得厚财利，但应忍口舌文明经商。",
    "合伙": "卜合伙之卦不吉恐伙计各有私心防是非口舌防阻失，勿合!",
    "置货": "置货一卦，初时劳苦，财利稀薄，八月起物价渐有提升，到底可得财利也。"
  },
  "出外": {
    "出外": "卜出外之卦似春花开之发，凡事勿疑有胆往外，有贵人扶助可得名利双全。"
  },
  "谋望求财": {
    "谋望": "十年辛苦在寒窗，一旦翻身入选场，幸得朝庭用智士，传扬天府姓名香。",
    "谋望解曰": "谋望;定成有贵人扶助，谋之即可随意但肖龙之人切不可谋，恐祸非失财也!",
    "求财": "正财初时稀薄，宜刻苦维持二，五，八，十一月有贵人扶助可得大财利偏财初有恐失，但到得底得大利!"
  },
  "学艺功名": {
    "学艺": "卜学技艺之事叶吉，宜坚心立志，勤恳向上，多问多想，自能得到名师传精艺也。",
    "功名": "现科文武功名皆中，荣宗耀祖封妻荫子。"
  },
  "行舟六畜": {
    "行舟": "行舟平安，顺风得利也。",
    "六畜": "初时六畜运未通，待到时来花自红。红花点点来庆贺，大好财利在秋冬。",
    "猪羊": "",
    "草龙": "",
    "三鸟": "",
    "田蚕": ""
  },
  "移徙": {
    "移徙": ""
  },
  "行人": {
    "诗": "",
    "解曰": ""
  },
  "婚姻": {
    "婚姻": "赤绳系足问前程，不用求谋事以成，丝牵月明缘份到，静坐好听凤凰鸣。",
    "解曰": "婚姻成之大吉，两人相合不用媒人，待月明之时便可下聘，就可成功也?"
  },
  "官讼": {
    "官讼": "",
    "解曰": ""
  },
  "失物": {
    "失物": "",
    "解曰": ""
  },
  "占病": {
    "占病": "",
    "解曰": ""
  },
  "其他": {
    "灶君": "",
    "阳基": "",
    "六甲": "",
    "子息": "",
    "祖山": "",
    "青草": ""
  }
}
